---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: spring-boot-conventions.tanzu.vmware.com.0.1.0
spec:
  refName: spring-boot-conventions.tanzu.vmware.com
  version: 0.1.0
  releasedAt: 2021-10-25T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.pivotal.io/tanzu-spring-boot-convention/spring-boot-conventions@sha256:5b28a693351b875112b8a2317929072e8c3b004655e2b66b19a97338582ae3ea
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - spring-boot-convention-server/server.yaml
      - ytt:
          paths:
          - "-"
          - bundle.yaml
      deploy:
      - kapp: {}