apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: services-toolkit.tanzu.vmware.com
spec:
  categories:
  - services
  displayName: Services Toolkit
  longDescription: |
    The Services Toolkit comprises a number of Kubernetes native components which support the management, lifecycle, discoverability and connectivity of Service Resources (databases, message queues, DNS records, etc.) on Kubernetes. These components are:
    * Service Offering
    * Service API Projection
    * Service Resource Replication
    * Service Resource Claims
  maintainers:
  - name: The Services Control Plane team
  providerName: VMware
  shortDescription: The Services Toolkit enables the management, lifecycle, discoverability and connectivity of Service Resources (databases, message queues, DNS records, etc.).
  supportDescription: https://tanzu.vmware.com/support
