apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: developer-conventions.tanzu.vmware.com
spec:
  displayName: Tanzu App Platform Develooper Conventions
  longDescription: Tanzu App Platform Developer Conventions
  shortDescription: Developer Conventions
