---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: conventions.appliveview.tanzu.vmware.com.1.1.0-build.3
spec:
  refName: conventions.appliveview.tanzu.vmware.com
  version: 1.1.0-build.3
  releaseNotes: |
        Release 1.1.0-build.3 of the App Live View Conventions package
  releasedAt: 2022-03-17T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-conventions-bundle@sha256:95f3c92e340f18f7c5586c52aabfb016a0a32ce4e6afa39f7244643d596ea1d9
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
