---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: appliveview.tanzu.vmware.com.0.3.0
spec:
  refName: appliveview.tanzu.vmware.com
  version: 0.3.0
  releaseNotes: |
        Release 0.3.0 of the App Live View package
  releasedAt: 2021-10-25T00:00:00Z
  valuesSchema:
    openAPIv3:
      title: appliveview.tanzu.vmware.com values schema
      properties:
        connector_namespaces:
          description: The namespaces in which ALV monitors the user's apps
          default: [default]
          type: array
          items:
            type: string
        server_namespace:
          description: The namespace to which ALV server is deployed
          default: app-live-view
          type: string   
        service_type:
          description: The service type for the Application Live View server can be LoadBalancer, NodePort, or ClusterIP
          default: LoadBalancer
          type: string       
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.tanzu.vmware.com/app-live-view/application-live-view-install-bundle:0.3.0
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
