apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: developer-conventions.tanzu.vmware.com.0.5.0-build.1
spec:
  refName: developer-conventions.tanzu.vmware.com
  version: 0.5.0-build.1
  valuesSchema:
    openAPIv3:
      properties: {}
  releasedAt: "2021-12-17T00:56:22Z"
  releaseNotes: |
    Developer Conventions contents package
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.tanzu.vmware.com/developer-conventions/developer-conventions-bundle:0.5.0-build.1
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
