---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: fluxcd/source-controller:v0.15.4
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.15.4
          url: fluxcd/source-controller:v0.15.4
  image: index.docker.io/fluxcd/source-controller@sha256:4a8c513efb7c38b35ecf5b92f1a1383c9bad00732ad5d17a0af79e7afe0e1cc9
- annotations:
    kbld.carvel.dev/id: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.28.0@sha256:bd27a0bfeaddc7a340617e2469b6fe9c5eeaee175dc34176c6ef2d6ba6025745
  image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256:bd27a0bfeaddc7a340617e2469b6fe9c5eeaee175dc34176c6ef2d6ba6025745
- annotations:
    kbld.carvel.dev/id: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.28.0@sha256:af6c1fc18a6dddc661baa5d44b7159c0e770d0e74bcbe3b4d7087274f9567fa0
  image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook@sha256:af6c1fc18a6dddc661baa5d44b7159c0e770d0e74bcbe3b4d7087274f9567fa0
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-cainjector:v1.5.3
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.5.3
          url: quay.io/jetstack/cert-manager-cainjector:v1.5.3
  image: quay.io/jetstack/cert-manager-cainjector-amd64@sha256:7f965f1ff37e5b1ad492d48cc178ade01d55554eaaff4d26a6142727dd1f6c6a
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-controller:v1.5.3
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.5.3
          url: quay.io/jetstack/cert-manager-controller:v1.5.3
  image: quay.io/jetstack/cert-manager-controller-amd64@sha256:1968107354ef295e6ae3c64a85e80a794fe3f498c92f6acb6d8db93c63286965
- annotations:
    kbld.carvel.dev/id: quay.io/jetstack/cert-manager-webhook:v1.5.3
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.5.3
          url: quay.io/jetstack/cert-manager-webhook:v1.5.3
  image: quay.io/jetstack/cert-manager-webhook-amd64@sha256:41ee98065ee0599d6af65c0e1cdf94bfa631d2bc4cb7567f571fd874eb38dd74
kind: ImagesLock
