apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ootb-templates.tanzu.vmware.com.0.5.0-build.1
spec:
  refName: ootb-templates.tanzu.vmware.com
  version: 0.5.0-build.1
  releasedAt: "2021-12-17T21:41:55Z"
  valuesSchema:
    openAPIv3:
      title: ootb-templates
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:8fc867cec8a28f6c6c4d03d4292ffee11517e46b6b01c123606eaecf8f385c57
      template:
      - ytt:
          ignoreUnknownComments: true
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
