apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ootb-templates.tanzu.vmware.com.0.7.1
spec:
  refName: ootb-templates.tanzu.vmware.com
  version: 0.7.1
  releasedAt: "2022-04-21T21:04:24Z"
  valuesSchema:
    openAPIv3:
      title: ootb-templates
      properties:
        excluded_templates:
          type: array
          items:
            type: string
          default: []
          description: List of templates to exclude from the installation (e.g. ['git-writer'])
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:8bf46cb3f54a4fdfbd9f96264f401779db861b90f21bf23a6e1df182dc27e304
      template:
      - ytt:
          ignoreUnknownComments: true
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
