## accelerator.apps.tanzu.vmware.com: Application Accelerator for VMware Tanzu
server:
  service_type: "LoadBalancer"
  watched_namespace: "default"
  engine_invocation_url: "http://acc-engine.accelerator-system.svc.cluster.local/invocations"
engine:
  service_type: "ClusterIP"

## api-portal.tanzu.vmware.com: API portal
apiPortalServer:
  replicaCount: 1
  sourceUrls: "https://petstore.swagger.io/v2/swagger.json,https://petstore3.swagger.io/api/v3/openapi.json"
  sourceUrlsCacheTtlSec: "300"
  sourceUrlsTimeoutSec: "10"

## appliveview.tanzu.vmware.com: Application Live View for VMware Tanzu
connector_namespaces: [default]
server_namespace: app-live-view

## buildservice.tanzu.vmware.com: Tanzu Build Service
# ca_cert_data:
# kp_default_repository:
# kp_default_repository_password:
# kp_default_repository_username:
# pull_from_tanzunet:
# tanzunet_username:
# tanzunet_password:

## cartographer.tanzu.vmware.com: Cartographer

## cnrs.tanzu.vmware.com: Cloud Native Runtimes
provider:
ingress:
  external:
    namespace:
  internal:
    namespace:
  reuse_crds: "false"
local_dns:
  domain:
  enable: "false"
pdb:
  enable: "true"

## controller.conventions.apps.tanzu.vmware.com: Convention Service for VMware Tanzu

## controller.source.apps.tanzu.vmware.com: Tanzu Source Controller

## developer-conventions.tanzu.vmware.com: Tanzu App Platform Develooper Conventions

## image-policy-webhook.signing.run.tanzu.vmware.com: Image Policy Webhook
warn_on_unmatched: "false"

## scp-toolkit.tanzu.vmware.com: SCP Toolkit

## scst-store.tanzu.vmware.com: Tanzu Supply Chain Security Tools - Store
api_host: "localhost"
api_port: 9443
app_service_type: "NodePort"
auth_proxy_host: "0.0.0.0"
auth_proxy_port: 84442
db_host: "metadata-postgres"
db_name: "metadata-store"
db_password:
db_port: "5432"
db_sslmode: "verify-full"
db_user: "metadata-store-user"
storageClassName: "manual"
use_cert_manager: "true"

## service-bindings.labs.vmware.com: Service Bindings for Kubernetes
