---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tbs.tanzu.vmware.com.1.2.2
spec:
  refName: tbs.tanzu.vmware.com
  version: 1.2.2
  releaseNotes: |
        Release 1.2.2 of the tbs app package
  valuesSchema:
    openAPIv3:
      title: tbs.tanzu.vmware.com values schema
      properties:
        docker_repository:
          type: string
          description: docker repository
          default: 
          examples:
          - registry.pivotal.io/adv_pkg_bundle
        docker_username:
          type: string
          description: registry username
          default: 
          examples:
          - janedoe@pivotal.io
        docker_password:
          type: string
          description: registry password
          default: 
          examples:
          - password
        tanzunet_username:
          type: string
          description: tanzunet registry username required for dependency updation feature
          default: 
          examples:
          - janedoe@pivotal.io
        tanzunet_password:
          type: string
          description: tanzunet registry password required for dependency updation feature
          default: 
          examples:
          - password   
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.pivotal.io/build-service/bundle:1.2.2
          secretRef:
            name: target-registry-secret
      template:
      - ytt:
          paths:
          - "values.yaml"
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
---
