apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  # This will be the name of our package
  name: tbs.tanzu.vmware.com
spec:
  displayName: "Tanzu Build Service"
  longDescription: "TBS consisting of all the manifests needed for installation"
  shortDescription: "tanzu build service"
  categories:
  - poc of packaging TBS