---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: grype.scanning.apps.tanzu.vmware.com.1.0.0-beta
spec:
  refName: grype.scanning.apps.tanzu.vmware.com
  version: 1.0.0-beta
  releaseNotes: |
    Beta release of the Supply Chain Security Tools - Scan package
  valuesSchema:
    openAPIv3:
      title: grype.scanning.apps.tanzu.vmware.com values schema
      properties:
        namespace:
          type: string
          description: Deployment namespace for the Scan Templates
          default: default
        resources:
          type: object
          properties:
            limits:
              type: object
              properties:
                cpu:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                  description: Limits describes the maximum amount of cpu resources allowed.
                  default: 1000m
            requests:
              type: object
              properties:
                cpu:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                  description: Requests describes the minimum amount of cpu resources required.
                  default: 250m
                memory:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                  description: Requests describes the minimum amount of memory resources required.
                  default: 128Mi
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/supply-chain-security-tools/grype-templates:v1.0.0-beta.1
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
