apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: image-policy-webhook.signing.run.tanzu.vmware.com
spec:
  displayName: "Image Policy Webhook"
  longDescription: "The Image Policy Webhook allows platform operators to define a policy that will restrict unsigned images on a Kubernetes cluster. This component contains logic to communicate with external registries and verify signatures on container images, making a decision based on the results of this verification. Currently, this component supports cosign signatures and its key formats."
  shortDescription: "The Image Policy Webhook allows platform operators to define a policy that will use cosign to verify signatures of container images"
  supportDescription: "https://tanzu.vmware.com/support"
  providerName: "VMware"
  categories:
  - policy
  maintainers:
  - "Adam Dawson"
  - "Andrés Torres"
  - "Denny Hoang"
  - "Der Wei Chan"
  - "Jackline Mutua"
  - "Kavitha Krishnan"
  - "Mauren Berti"
  - "Robert Szumlakowski"
