---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: controller.source.apps.tanzu.vmware.com.0.2.0
spec:
  refName: controller.source.apps.tanzu.vmware.com
  version: 0.2.0
  releasedAt: 2021-11-18T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-source-controller/source-controller-bundle@sha256:d4e9bca1c7520346dbc26087e8470380fd5339e4b3c3bf97d8e64bb58efc4c2c
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/source-controller.yaml
      - ytt:
          paths:
          - "-"
          - bundle.yaml
      deploy:
      - kapp: {}