apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ootb-supply-chain-basic.tanzu.vmware.com.0.3.0-build.2
spec:
  refName: ootb-supply-chain-basic.tanzu.vmware.com
  version: 0.3.0-build.2
  releasedAt: "2021-10-27T16:00:20Z"
  valuesSchema:
    openAPIv3:
      title: ootb-supply-chain-basic
      properties:
        cluster_builder:
          type: string
          description: Name of the Tanzu Build Service (TBS) ClusterBuilder to use by default on image objects managed by the supply chain.
          default: default
          examples:
          - default
        service_account:
          type: string
          description: Name of the service account in the namespace where the Workload is submitted to utilize for providing registry credentials to Tanzu Build Service (TBS) Image objects as well as deploying the application.
          default: default
          examples:
          - default
        registry.server:
          type: string
          description: Name of the registry server where application images should be pushed to.
          default: index.docker.io
          examples:
          - index.docker.io
          - gcr.io
        registry.repository:
          type: string
          description: Name of the repository in the image registry server where the application images from the workloads should be pushed to (required).
          examples:
          - web-team
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/ootb-supply-chain-basic/ootb-supply-chain-basic@sha256:d8f3ddd7475bb9ba7a550ee10ce8aba82ae3e1f15db178bc7c616967ed2e2f88
      template:
      - ytt:
          ignoreUnknownComments: true
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
