apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer.tanzu.vmware.com.0.0.6
spec:
  refName: cartographer.tanzu.vmware.com
  version: 0.0.6
  releaseNotes: |-
    Initial Release of Supply Chain Choreographer - see
    https://github.com/vmware-tanzu/cartographer/blob/main/site/content/docs/about.md
  releasedAt: 2021-09-22T21:31:59Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.tanzu.vmware.com/supply-chain-choreographer/cartographer@sha256:f7e402cfa7c9404afdb51f9c6967c688e2595660b9335429ed5a880fc2caa80f
      template:
      - ytt:
          ignoreUnknownComments: true
          inline:
            paths:
              namespace.yaml: |-
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: cartographer-system
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
