apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ootb-templates.tanzu.vmware.com.0.5.1
spec:
  refName: ootb-templates.tanzu.vmware.com
  version: 0.5.1
  releasedAt: "2022-01-07T14:53:11Z"
  valuesSchema:
    openAPIv3:
      title: ootb-templates
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:2d346ff49465eb48be068cf4e4a4cad90d1c6dc2ad35c992a0794ca180838f3f
      template:
      - ytt:
          ignoreUnknownComments: true
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
