---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cnrs.tanzu.vmware.com.1.0.1
spec:
  refName: cnrs.tanzu.vmware.com
  version: 1.0.1
  releasedAt: 2021-07-30T00:00:00Z
  releaseNotes: |
        Release 1.0.1 of the Cloud Native Runtimes app package
  capacityRequirementsDescription: Cluster with one node Requires >6 CPUS, >6.0GB RAM, >30GB storage, cluster with multiple nodes Requires >2 CPUS, >4.0GB RAM, >20GB storage
  valuesSchema:
    openAPIv3:
      title: cnrs.tanzu.vmware.com values schema
      properties:
        registry.server:
          type: registry server
          default: 
          examples:
          - registry.pivotal.io
        registry.username:
          type: string
          description: registry username
          default: 
          examples:
          - janedoe@pivotal.io
        registry.password:
          type: string
          description: registry password
          default: 
        provider:
          type: string
          description: Kubernetes cluster provider
          default: 
          examples:
          - local, tkgs
        local_dns:
          type: string
          description: 
          default: 
          examples:
          - dns
        ingress.reuse_crds:
          type: string
          description: set true to reuse existing Contour instance
          default: false
        ingress.external.namespace:
          type: string
          description: external namespace
          default: 
        ingress.internal.namespace:
          type: string
          description: internal namespace
          default: 
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: projects.registry.vmware.com/tanzu_serverless/release@sha256:aff798e78aeeb9b5404c33ac1ddfcbe962271b496433e267d94378e2bf911366
          secretRef:
            name: tap-registry
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/kbld.yaml
          - config/serving
          - config/net-contour
          - config/eventing
          - config/net-certmanager
          - config/discovery
          - config/aws-event-sources
      - ytt:
          ignoreUnknownComments: true
          paths:
          - '-'
          - config/ytt/
          - config/kapp.yaml
      deploy:
      - kapp: {}
