apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-telemetry.tanzu.vmware.com.0.2.0
spec:
  refName: tap-telemetry.tanzu.vmware.com
  version: 0.2.0
  releasedAt: "2021-11-30T00:00:00Z"
  releaseNotes: Initial release of tap-telemetry.
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-telemetry/telemetry-bundle@sha256:e1b3dae12a0b225def05a65992d9edce12bfa4e37955bce613fde622d73c760b
      template:
      - ytt:
          paths:
          - config.yaml
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
