apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: buildservice.tanzu.vmware.com.1.6.0
spec:
  refName: buildservice.tanzu.vmware.com
  version: 1.6.0
  capacityRequirementsDescription: Cluster with nodes > 50GB ephemeral storage, Registry > 10GB available space
  releaseNotes: https://docs.vmware.com/en/VMware-Tanzu-Build-Service/index.html
  releasedAt: "2022-06-10T00:00:00Z"
  valuesSchema:
    openAPIv3:
      properties:
        kp_default_repository:
          type: string
          description: "Docker repository used for builder images and dependencies"
          examples:
            - registry.io/build-service
        kp_default_repository_username:
          type: string
          description: "Username for kp_default_repository"
          examples:
            - janedoe@vmware.com
            - "_json_key"
        kp_default_repository_password:
          type: string
          description: "Password for kp_default_repository"
          examples:
            - password
        kp_default_repository_secret.name:
          type: string
          description: "Secret name for kp_default_repository credentials of type kubernetes.io/dockerconfigjson. Mutually exclusive with kp_default_repository_username/password."
        kp_default_repository_secret.namespace:
          type: string
          description: "Secret namespace for kp_default_repository credentials. Mutually exclusive with kp_default_repository_username/password."
        kp_default_repository_aws_iam_role_arn:
          type: string
          description: "AWS IAM role ARN to authenticate to ECR on EKS for kp_default_repository. Mutually exclusive with kp_default_repository_username/password."
        exclude_dependencies:
          type: bool
          description: "Optional: Exclude dependencies from automatically being imported, allowing dependencies to be installed separately."
        enable_automatic_dependency_updates:
          type: bool
          description: "Optional: Allow automatic import of new dependency updates from Tanzunet."
        tanzunet_username:
          type: string
          description: "Optional: Tanzunet registry username required for enabling automatic updates."
          examples:
            - janedoe@vmware.com
        tanzunet_password:
          type: string
          description: "Optional: Tanzunet registry password required for enabling automatic updates."
          examples:
            - password
        tanzunet_secret.name:
          type: string
          description: "Optional: Secret name for Tanzunet registry credentials of type kubernetes.io/dockerconfigjson. Mutually exclusive with tanzunet_username/password."
        tanzunet_secret.namespace:
          type: string
          description: "Optional: Secret namespace for Tanzunet registry credentials. Mutually exclusive with tanzunet_username/password."
        ca_cert_data:
          type: string
          description: "Optional: TBS registry ca certificate"
        http_proxy:
          type: string
          description: "Optional: the HTTP proxy to use for network traffic."
        https_proxy:
          type: string
          description: "Optional: the HTTPS proxy to use for network traffic."
        no_proxy:
          type: string
          description: "Optional: A comma-separated list of hostnames, IP addresses, or IP ranges in CIDR format that should not use a proxy."
        descriptor_version:
          type: string
          description: "Optional: Version of descriptor to use during install. This will override the version installed by default."
        descriptor_name:
          type: string
          description: "Optional: Name of descriptor to use for for automatic updates (required for dependency updater feature)"
          examples:
            - lite
            - full
        enable_synced_secrets:
          type: bool
          description: "Optional: Enable secret syncing functionality to provide credentials to automatically pull builder and run images."
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: dev.registry.tanzu.vmware.com/build-service/bundle@sha256:2f421239abf72526ca114350d1428abf2c9fcc330d307a9e6c9de78b54d62d87
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - '-'
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
