---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "workshops.learningcenter.tanzu.vmware.com.1.0.5-build.1"
spec:
  refName: "workshops.learningcenter.tanzu.vmware.com"
  version: "1.0.5-build.1"
  releasedAt: "2021-10-28T22:51:27Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:f2ec6e788b45e9a66ee361f1457f3f1446d8aa9a329f35b25dfc1a49e97cd767"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}