---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: controller.conventions.apps.tanzu.vmware.com.0.4.2
spec:
  refName: controller.conventions.apps.tanzu.vmware.com
  version: 0.4.2
  releasedAt: 2021-09-16T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.tanzu.vmware.com/tanzu-convention-service/convention-controller-bundle@sha256:fcf95067b792e8a043cc51638fcd0001875d2895bf09349b34a9d2b0056850a1
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/namespace.yaml
          - config/convention-controller.yaml
      - ytt:
          paths:
          - "-"
          - bundle.yaml
      deploy:
      - kapp: {}
