---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: conventions.appliveview.tanzu.vmware.com.1.1.0-build.1
spec:
  refName: conventions.appliveview.tanzu.vmware.com
  version: 1.1.0-build.1
  releaseNotes: |
        Release 1.1.0-build.1 of the App Live View Conventions package
  releasedAt: 2022-02-24T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-conventions-bundle@sha256:9b71bc1a8ddab2c627782c0b5433e745742d99b88094050af6d986d7b59bf596
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}