---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: dev.registry.pivotal.io/app-accelerator/acc-install-bundle:0.2.0-dev
  image: dev.registry.pivotal.io/app-accelerator/acc-install-bundle@sha256:00b45a328cb0f331ae646e5986f78628bf1b10b2ec2d1ad6ce2467664149310b
- annotations:
    kbld.carvel.dev/id: projects.registry.vmware.com/tanzu_serverless/release@sha256:aff798e78aeeb9b5404c33ac1ddfcbe962271b496433e267d94378e2bf911366
  image: projects.registry.vmware.com/tanzu_serverless/release@sha256:aff798e78aeeb9b5404c33ac1ddfcbe962271b496433e267d94378e2bf911366
- annotations:
    kbld.carvel.dev/id: registry.pivotal.io/app-live-view/application-live-view-install-bundle:0.1.0
  image: registry.pivotal.io/app-live-view/application-live-view-install-bundle@sha256:349210e9bef0ca8b1da90ad9151798966354c2e6018b56b7fd485cbd5a1c7f9b
kind: ImagesLock
