---
create_namespaces:
  - my-apps
  - tap-install
innerloop:
  workload:
    name: tanzu-java-web-app
    namespace: my-apps
    url: "tanzu-java-web-app.my-apps.example.com"
    gitrepository: https://github.com/dapdelivery/tanzu-java-web-app
    yaml_file: resources/innerloop/tanzu-web-app-workload.yaml
    application_file_path: "tanzu-java-web-app/src/main/java/com/example/springboot/HelloController.java"
    new_string: "Greetings from Spring Boot + TAP!"
    original_string: "Greetings from Spring Boot + Tanzu!"
    build_name_suffix: -build-1
    image_delivery_suffix: -delivery
package_repository:
  image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.0.1-build.7
  name: tanzu-tap-repository
  namespace: tap-install
non-tanzu-repository:
  - repository: gcr.io/tap-ci/tap-packages-test/tap-packages
    username: <GCR-SA-USERNAME>
    passwordType: key
    password: <GCR-SA-PASSWORD>
    server: gcr.io
  - repository: tappackagestest.azurecr.io/tap-packages
    username: <ACR-ID>
    password: <ACR-PASSWORD>
  - repository: dev.registry.tanzu.vmware.com/tanzu-application-platform/tap-ci-test/tap-packages
    server: tappackagestest.azurecr.io
    username: <DEV-TANZU-USERNAME>
    password: <DEV-TANZU-PASSWORD>
    server: dev.registry.tanzu.vmware.com
tap_registry_secret:
  export: true
  name: tap-registry
  namespace: tap-install
  password: <TANZUNET-PASSWORD>
  username: <TANZUNET-USERNAME>
  registry: dev.registry.tanzu.vmware.com
registry_credentials_secret:
  export: false
  name: registry-credentials
  namespace: my-apps
  password: <TANZUNET-PASSWORD>
  registry: <TANZUNET-USERNAME>
  username: svc.dap-delivery@vmware.com
tap:
  name: tap
  namespace: tap-install
  package_name: tap.tanzu.vmware.com
  poll_timeout: 30m
  values_schema_file: tap-values.yaml
  version: 1.0.1-build.7
tanzu-cluster-essentials:
  tanzunet_host: https://network.tanzu.vmware.com
  tanzunet_api_token: <TANZUNET-API-TOKEN>
  product_file_id: 1191987
  release_version: 1.1.0
  product_slug: tanzu-cluster-essentials
  download_bundle: tanzu-cluster-essentials-linux-amd64-1.1.0.tgz
  install_bundle: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:ab0a3539da241a6ea59c75c0743e9058511d7c56312ea3906178ec0f3491f51d
  install_registry_hostname: registry.tanzu.vmware.com
  install_registry_username: <TANZUNET-USERNAME>
  install_registry_password: <TANZUNET-PASSWORD>
git-credentials:
  username: dapdelivery
  email: svc.dapdelivery@gmail.com
upgrade-versions:
  image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.0.2
  tap-version: 1.0.2
  upgrade-image: dev.registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.1.0-build.15
  upgrade-tap-version: 1.1.0-build.15
multicluster:
  view-cluster-context: <VIEW-CLUSTER-CONTEXT>
  view-tap-values-file: view-tap-values.yaml
  iterate-cluster-context: <ITERATE-CLUSTER-CONTEXT>
  iterate-tap-values-file: iterate-tap-values.yaml

