accelerator:
    server:
        service_type: ClusterIP
buildservice:
    kp_default_repository: <KP-DEFAULT-REPOSITORY>
    kp_default_repository_password: <KP-DEFAULT-REPOSITORY-PASSWORD>
    kp_default_repository_username: <KP-DEFAULT-REPOSITORY-USERNAME>
    tanzunet_password: <TANZUNET-PASSWORD>
    tanzunet_username: <TANZUNET-USERNAME>
    descriptor_name: "tap-1.0.0-lite"
    enable_automatic_dependency_updates: true
ceip_policy_disclosed: true
contour:
    envoy:
        service:
            type: LoadBalancer
grype:
    namespace: my-apps
    targetImagePullSecret: registry-credentials
learningcenter:
    ingressDomain: educates.tanzu.vmwware.com
ootb_supply_chain_basic:
    gitops:
        ssh_secret: ""
    registry:
        repository: <REPOSITORY>
        server: <SERVER>
ootb_supply_chain_testing:
    gitops:
        ssh_secret: ""
    registry:
        repository: <REPOSITORY>
        server: <SERVER>
ootb_supply_chain_testing_scanning:
    gitops:
        ssh_secret: ""
    registry:
        repository: <REPOSITORY>
        server: <SERVER>
profile: full
supply_chain: basic
tap_gui:
    service_type: LoadBalancer
convention_controller: 
    ca-cert-data:
source_controller:
    ca-cert-data:
