profile: view
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

contour:
  envoy:
    service:
      type: LoadBalancer #NodePort can be used if your Kubernetes cluster doesn't support LoadBalancing

learningcenter:
    ingressDomain: educates.tanzu.vmwware.com

tap_gui:
  service_type: LoadBalancer
  ingressEnabled: false

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

appliveview:
