profile: view
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

accelerator:
    server:
        service_type: ClusterIP
        
contour:
  envoy:
    service:
      type: LoadBalancer #NodePort can be used if your Kubernetes cluster doesn't support LoadBalancing

learningcenter:
  ingressDomain: educates.tanzu.vmwware.com

tap_gui:
  service_type: LoadBalancer
  ingressEnabled: false
  # app_config:
  #   app:
  #     baseUrl: 
  #   backend:
  #     baseUrl: 
  #     cors:
  #       origin: 
  #   kubernetes:
  #     serviceLocatorMethod:
  #       type: 'multiTenant'
  #     clusterLocatorMethods:
  #       - type: 'config'
  #         clusters:
  #           - url: 
  #             name: iterate-cluster
  #             authProvider: serviceAccount
  #             serviceAccountToken: 
  #             skipTLSVerify: true

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

#appliveview:
 # ingressEnabled: TRUE-OR-FALSE-VALUE
  #ingressDomain: APP-LIVE-VIEW-INGRESS-DOMAIN