#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full]):
#@ if profiles.is_pkg_enabled("api-portal.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: api-portal
  namespace: tap-install
  annotations: 
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: api-portal.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.8
  values:
  - secretRef:
      name: api-portal-values
---
apiVersion: v1
kind: Secret
metadata:
  name: api-portal-values
  namespace: tap-install
stringData:
  values.yml: #@ yaml.encode(data.values.api_portal)

#@ end
#@ end
