#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:overlay", "overlay")
#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.light, profiles.iterate, profiles.run]):
#@ if profiles.is_pkg_enabled("cnrs.tanzu.vmware.com"):

#@ def cnrsOverlay():
ingress:
  external:
    #@overlay/match missing_ok=True
    namespace: #@ data.values.contour.namespace
  internal:
    #@overlay/match missing_ok=True
    namespace: #@ data.values.contour.namespace
#@ end

#@ def cnrsValues():
#@ if hasattr(data.values, "contour"):
#@ if data.values.contour.namespace:
#@ return overlay.apply(data.values.cnrs, cnrsOverlay())
#@ end
#@ return data.values.cnrs
#@ end
#@ end
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cnrs
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    kapp.k14s.io/change-rule.contour: "upsert after upserting contour"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: cnrs.tanzu.vmware.com
    versionSelection:
      constraints: 1.1.0
  values:
    - secretRef:
        name: cnrs-values
---
apiVersion: v1
kind: Secret
metadata:
  name: cnrs-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(cnrsValues())

#@ end
#@ end
