



---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: contour
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.18.2+tap.2
      prereleases: {}
  values:
  - secretRef:
      name: contour-values
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-values
  namespace: tap-install
stringData:
  values.yaml: |
    namespace: contour-external
    envoy:
      service:
        type: LoadBalancer




