#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.dev_light, profiles.operator_light]):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: conventions-controller
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: conventions
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: controller.conventions.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.4.2

#@ end
