#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.dev, profiles.build, profiles.run]):
#@ if profiles.is_pkg_enabled("controller.conventions.apps.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: conventions-controller
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: conventions
    kapp.k14s.io/change-rule.cert-manager: "upsert after upserting cert-manager" 
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: controller.conventions.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.4.2

#@ end
#@ end
