#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:overlay", "overlay")
#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled(profiles.full) and data.values.supply_chain == "testing":

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: default-supply-chain-testing
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting cartographer"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: default-supply-chain-testing.tanzu.vmware.com
    versionSelection:
      constraints: 0.2.0
  values:
  - secretRef:
      name: default-supply-chain-testing-values

#@ def values():
#@overlay/match missing_ok=True
registry:
  #@overlay/match missing_ok=True
  server: #@ data.values.rw_app_registry.server_repo.split("/", 1)[0]
  #@overlay/match missing_ok=True
  repository: #@ data.values.rw_app_registry.server_repo.split("/", 1)[1]
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: default-supply-chain-testing-values
  namespace: tap-install
type: Opaque
stringData:
  values.yml: #@ yaml.encode(overlay.apply(data.values.default_supply_chain_testing, values()))

#@ end
