#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.dev, profiles.build, profiles.run]):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluxcd-source-controller
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: fluxcd.source.controller.tanzu.vmware.com
    versionSelection:
      constraints: 0.16.0

#@ end

