#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.tbd]):
#@ if profiles.is_pkg_enabled("learningcenter.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: learningcenter
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: learningcenter
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
    kapp.k14s.io/change-rule.contour: "upsert after upserting contour"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: learningcenter.tanzu.vmware.com
    versionSelection:
      constraints: 0.1.0
  values:
  - secretRef:
      name: learningcenter-values
---
apiVersion: v1
kind: Secret
metadata:
  name: learningcenter-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(data.values.learningcenter)

#@ end
#@ end
