#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.tbd]):
#@ if profiles.is_pkg_enabled("workshops.learningcenter.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: learningcenter-workshops
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.learningcenter: "upsert after upserting learningcenter"
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: workshops.learningcenter.tanzu.vmware.com
    versionSelection:
      constraints: 0.1.0

#@ end
#@ end
