#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.build]):
#@ if profiles.is_pkg_enabled("scst-store.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scst-store
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting cert-manager" 
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: scst-store.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-build.4
      prereleases: {}

#@ end
#@ end
