#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.light, profiles.build]):
#@ if profiles.is_pkg_enabled("ootb-templates.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: ootb-templates
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.cartographer: "upsert after upserting cartographer"
    kapp.k14s.io/change-group: ootb-templates
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: ootb-templates.tanzu.vmware.com
    versionSelection:
      constraints: 0.6.0

#@ end
#@ end
