#@ load("_profiles.star", "profiles")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if profiles.is_any_enabled([profiles.full, profiles.light, profiles.iterate, profiles.build, profiles.run]):
#@ if profiles.is_pkg_enabled("ootb-templates.tanzu.vmware.com"):

#@ def ootb_templates_values():
#@   pkg_values_dict = struct.decode(data.values.ootb_templates)
#@
#@   if not profiles.is_any_enabled([profiles.run]):
#@     return struct.encode(pkg_values_dict)
#@   end
#@
#@   if 'excluded_templates' not in pkg_values_dict:
#@     pkg_values_dict['excluded_templates'] = []
#@   end
#@
#@   pkg_values_dict['excluded_templates'].append('git-writer')
#@   pkg_values_dict['excluded_templates'].append('image-writer')
#@   return pkg_values_dict
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: ootb-templates
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.cartographer: "upsert after upserting cartographer"
    kapp.k14s.io/change-group: ootb-templates
    kapp.k14s.io/change-rule.serviceaccount: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: ootb-templates.tanzu.vmware.com
    versionSelection:
      constraints: 0.7.0-build.2
      prereleases: {}
  values:
  - secretRef:
      name: ootb-templates-values

---
apiVersion: v1
kind: Secret
metadata:
  name: ootb-templates-values
  namespace: tap-install
type: Opaque
stringData:
  values.yml: #@ yaml.encode(ootb_templates_values())

#@ end
#@ end
