#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full]):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scan-controller
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: scancontroller
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: scanning.apps.tanzu.vmware.com
    versionSelection:
      constraints: 1.0.0-beta.2
      prereleases: {}

#@ end
