#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.light, profiles.run]):
#@ if profiles.is_pkg_enabled("service-bindings.labs.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: service-bindings
  namespace: tap-install
  annotations: 
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: service-bindings.labs.vmware.com
    versionSelection:
      constraints: 0.6.0
      prereleases: {}

#@ end
#@ end
