#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.dev_light, profiles.operator_light]):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scp-toolkit
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: services-toolkit.tanzu.vmware.com
    versionSelection:
      constraints: 0.4.0-rc.1
      prereleases: {}

#@ end
