#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.dev_light]):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: source-controller
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: controller.source.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.2.0

#@ end
