#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.dev_light, profiles.operator_light]):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: spring-boot-conventions
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: spring-boot-conventions.tanzu.vmware.com
    versionSelection:
      constraints: 0.1.1

#@ end
