#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:overlay", "overlay")
#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.workspace, profiles.build]):
#@ if profiles.is_pkg_enabled("buildservice.tanzu.vmware.com"):

#@ def user_values():
#@overlay/match by=overlay.all
#@overlay/match-child-defaults missing_ok=True
--- #@ data.values.buildservice
#@ end

#@ def default_values():
---
descriptor_name: tap-1.0.0-lite
#@ if/end profiles.is_any_enabled([profiles.workspace]):
disable_smart_warmer: true
#@ end


---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: buildservice
  namespace: tap-install
  annotations: 
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: buildservice.tanzu.vmware.com
    versionSelection:
      constraints: 1.4.2
      prereleases: {}
  values:
  - secretRef:
      name: buildservice-values
---
apiVersion: v1
kind: Secret
metadata:
  name: buildservice-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(overlay.apply(default_values(), user_values()))

#@ end
#@ end
