#@ load("_profiles.star", "profiles")

#@ if profiles.is_any_enabled([profiles.full, profiles.iterate, profiles.build, profiles.run]):
#@ if profiles.is_pkg_enabled("tekton.tanzu.vmware.com"):

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton-pipelines
  namespace: tap-install
  annotations: 
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: tekton.tanzu.vmware.com
    versionSelection:
      constraints: 0.30.0

#@ end
#@ end
