#@data/values-schema
---
#! enum: "full", "dev-light"
profile: full

install_cert_manager: true
install_tekton: true

#@schema/type any=True
api_portal: {}

#@schema/type any=True
accelerator: {}

#@schema/type any=True
appliveview: {}

#@schema/type any=True
cartographer: {}

#@schema/type any=True
cnrs: {}

supply_chain: basic

#@schema/type any=True
ootb_supply_chain_basic: {}

#@schema/type any=True
ootb_supply_chain_testing: {}

#@schema/type any=True
ootb_supply_chain_testing_scanning: {}

#@schema/type any=True
image_policy_webhook: {}

#@schema/type any=True
grype: {}

#@schema/type any=True
buildservice: {}

#@schema/type any=True
tap_gui: {}

#@schema/type any=True
learningcenter: {}
