apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: grype.scanning.apps.tanzu.vmware.com.1.0.0
spec:
  refName: grype.scanning.apps.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: Supply Chain Security Tools - Scan (Grype Scanner) v1.0.0
  releasedAt: 2021-12-15T22:32:00Z
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/supply-chain-security-tools/grype-templates:v1.0.0-build.4@sha256:4852ff2f9cca4960db5fc691087e63e5896d7794828c7cdbb6e6d92fc8805710
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      title: grype.scanning.apps.tanzu.vmware.com.1.0.0 values schema
      properties:
        namespace:
          type: string
          description: Deployment namespace for the Scan Templates
          default: default
        targetSourceSshSecret:
          type: string
          description: Reference to the secret containing SSH credentials for cloning private repositories.
          default: ""
        targetImagePullSecret:
          type: string
          description: Reference to the secret used for pulling images from private registry.
          default: ""
        resources:
          type: object
          properties:
            limits:
              type: object
              properties:
                cpu:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                  description: Limits describes the maximum amount of cpu resources allowed.
                  default: 1000m
            requests:
              type: object
              properties:
                cpu:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                  description: Requests describes the minimum amount of cpu resources required.
                  default: 250m
                memory:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                  description: Requests describes the minimum amount of memory resources required.
                  default: 128Mi
