apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap.tanzu.vmware.com.0.1.0
spec:
  refName: tap.tanzu.vmware.com
  version: 0.1.0
  releaseNotes: |
    Beta release 0.3.0 of Tanzu Application Platform.
    This package allows to select which set of packages to install via profile data value.
  releasedAt: "2021-10-19T00:00:00Z"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image:  dev.registry.tanzu.vmware.com/tanzu-application-platform/tap-profiles:0.1.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        profile:
          type: string
          default: full
          description: "Valid values one of: full, dev-light, operator-light, shared-tools"
        supply_chain:
          type: string
          default: ""
          description: "Valid values one of: <empty>, testing"
        rw_app_registry:
          type: object
          additionalProperties: false
          description: "Read-write registry credentials"
          properties:
            server_repo:
              type: string
              default: ""
            username:
              type: string
              default: ""
            password:
              type: string
              default: ""
        install_cert_manager:
          type: boolean
          default: true
        install_flux:
          type: boolean
          default: true
        install_tekton:
          type: boolean
          default: true
        api_portal:
          type: object
          additionalProperties: true
          properties: {}
        app_accelerator:
          type: object
          additionalProperties: true
          properties:
            server:
              type: object
              additionalProperties: true
              properties:
                service_type:
                  type: string
                  default: NodePort
                watched_namespace:
                  type: string
                  default: default
                engine_invocation_url:
                  type: string
                  default: http://acc-engine.accelerator-system.svc.cluster.local/invocations
            engine:
              type: object
              additionalProperties: true
              properties:
                service_type:
                  type: string
                  default: ClusterIP
        app_live_view:
          type: object
          additionalProperties: true
          properties:
            server_namespace:
              type: string
              default: app-live-view
        cnrs:
          type: object
          additionalProperties: true
          properties:
            provider:
              type: string
              default: local
        default_supply_chain:
          type: object
          additionalProperties: true
          properties: {}
        default_supply_chain_testing:
          type: object
          additionalProperties: true
          properties: {}
        image_policy_webhook:
          type: object
          additionalProperties: true
          properties:
            warn_on_unmatched:
              type: boolean
              default: true
        buildservice:
          type: object
          additionalProperties: true
          properties:
            tanzunet_username:
              type: string
              default: ""
            tanzunet_password:
              type: string
              default: ""
