---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "workshops.learningcenter.tanzu.vmware.com.1.0.7-build.6"
spec:
  refName: "workshops.learningcenter.tanzu.vmware.com"
  version: "1.0.7-build.6"
  releasedAt: "2021-11-25T20:32:45Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:8059eae6cf4f4b24590f7f372e3be481b118bb80bf1ca2b95f0fbfb4f4e486a4"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}