---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: source-controller.tanzu.vmware.com
spec:
  displayName: "Tanzu Source Controller"
  longDescription: "Tanzu Source Controller enables app devs to create/update workloads from local or remote source code repository."
  shortDescription: "Tanzu Source Controller enables workload create/update from source code."
  providerName: "VMware"
  maintainers:
  - name: "Scott Andrews"
  - name: "Rashed Kamal"
  supportDescription: "https://tanzu.vmware.com/support"
