---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: accelerator.apps.tanzu.vmware.com
spec:
  displayName: "Application Accelerator for VMware Tanzu"
  longDescription: "Application Accelerator is used to create new projects and configurations which follow enterprise standards."
  shortDescription: "Used to create new projects and configurations."
  providerName: "VMware"
  maintainers:
  - name: "Thomas Risberg"
  - name: "Diego Wong"
  supportDescription: "Support available from VMware. Refer to the VMware Product Guide for specific support terms."
