---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: spring-boot-conventions.tanzu.vmware.com.0.4.1
spec:
  refName: spring-boot-conventions.tanzu.vmware.com
  version: 0.4.1
  releasedAt: 2022-06-09T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-spring-boot-convention/spring-boot-conventions@sha256:a9a72b5196f1219a79ec41fb3ed3c5a2a529b3f0810ac1948c47cabf113b8d8d
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - spring-boot-convention-server/server.yaml
      - ytt:
          paths:
          - '-'
          - spring-boot-convention-server/bundle.yaml
      deploy:
      - kapp: {}