---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package:1.0.8
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 1.0.8
          url: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package:1.0.8
  image: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package@sha256:5622312b61dccac7f7fac63930c6285d35d0cb32a0442ef4d05c8a299d361cc9
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package@sha256:10b846f2b6b2ef544b2ffe3bbc28b745161be43982b3b23a460ffc8967941e6d
  image: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package@sha256:10b846f2b6b2ef544b2ffe3bbc28b745161be43982b3b23a460ffc8967941e6d
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/app-accelerator/acc-install-bundle@sha256:b918aa75d09174507b09fb2248bfbda8b204c5acc10cd28eda3cbbbb3b358643
  image: dev.registry.tanzu.vmware.com/app-accelerator/acc-install-bundle@sha256:b918aa75d09174507b09fb2248bfbda8b204c5acc10cd28eda3cbbbb3b358643
kind: ImagesLock
