apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap.tanzu.vmware.com.1.2.0-build.7
spec:
  refName: tap.tanzu.vmware.com
  version: 1.2.0-build.7
  releaseNotes: Release of 1.2.0-build.7 Tanzu Application Platform. This package allows to select which set of packages to install via profile data value.
  releasedAt: "2022-06-06T00:00:00Z"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/tap@sha256:61c2d41ab596e23c62f6b846a5133e264671fd5b5db87904ac04ef9cd48b1a12
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        profile:
          type: string
          default: full
          description: 'Profile to install. Valid values: full, light, iterate, build, run, view'
        supply_chain:
          type: string
          default: basic
          description: 'Supply chain to install. Valid values: basic, testing, testing_scanning'
        excluded_packages:
          type: array
          items:
            type: string
          default: []
          description: List of packages to exclude from installation (e.g. [tap-gui.tanzu.vmware.com])
        shared:
          type: object
          properties:
            ca_cert_data:
              type: string
              default: ""
              description: 'Optional: PEM Encoded certificate data to trust TLS connections with a private CA.'
            ingress_domain:
              type: string
              default: ""
              description: 'Optional: Domain name to be used in service routes and hostnames for instances of TAP components.'
          description: Common properties shared across multiple components
        api_portal:
          type: object
          additionalProperties: true
          properties: {}
          description: API Portal configuration
        accelerator:
          type: object
          additionalProperties: true
          properties: {}
          description: Accelerator configuration
        appliveview:
          type: object
          additionalProperties: true
          properties: {}
          description: App Live View configuration
        cnrs:
          type: object
          additionalProperties: true
          description: Cloud Native Runtimes configuration
          properties:
            ingress:
              type: object
              properties:
                reuse_crds:
                  type: boolean
                  description: 'Optional: Only valid if a Contour instance already present in the cluster. Set to "true" if you want CNR to re-use the cluster''s existing Contour CRDs.'
                  default: true
                external:
                  type: object
                  properties:
                    namespace:
                      type: string
                      description: 'Optional: Only valid if a Contour instance already present in the cluster. Specify a namespace where an existing Contour is installed on your cluster (for external services) if you want CNR to use your Contour instance.'
                      default: tanzu-system-ingress
                internal:
                  type: object
                  properties:
                    namespace:
                      type: string
                      description: 'Optional: Only valid if a Contour instance already present in the cluster. Specify a namespace where an existing Contour is installed on your cluster (for internal services) if you want CNR to use your Contour instance.'
                      default: tanzu-system-ingress
        ootb_supply_chain_basic:
          type: object
          additionalProperties: true
          properties: {}
          description: OOTB Supply Chain Basic configuration
        ootb_supply_chain_testing:
          type: object
          additionalProperties: true
          properties: {}
          description: OOTB Supply Chain Testing configuration
        ootb_supply_chain_testing_scanning:
          type: object
          additionalProperties: true
          properties: {}
          description: OOTB Supply Chain Testing Scanning configuration
        image_policy_webhook:
          type: object
          additionalProperties: true
          properties: {}
          description: Image Policy Webhook configuration
        buildservice:
          type: object
          description: Build Service configuration
          properties:
            kp_default_repository:
              type: string
              description: docker repository (required)
              examples:
              - registry.io/build-service
            kp_default_repository_username:
              type: string
              description: registry username (required)
              examples:
              - janedoe@vmware.com
            kp_default_repository_password:
              type: string
              description: registry password (required)
              examples:
              - password
            kp_default_repository_secret.name:
              description: Secret name for kp_default_repository credentials of type kubernetes.io/dockerconfigjson. Mutually exclusive with kp_default_repository_username/password.
              type: string
            kp_default_repository_secret.namespace:
              description: Secret namespace for kp_default_repository credentials. Mutually exclusive with kp_default_repository_username/password.
              type: string
            tanzunet_username:
              type: string
              description: tanzunet registry username (required for dependency updater feature)
              examples:
              - janedoe@vmware.com
            tanzunet_password:
              type: string
              description: tanzunet registry password (required for dependency updater feature)
              examples:
              - password
            tanzunet_secret.name:
              description: 'Optional: Secret name for tanzu network registry credentials of type kubernetes.io/dockerconfigjson. Mutually exclusive with tanzunet_username/password.'
              type: string
            tanzunet_secret.namespace:
              description: 'Optional: Secret namespace for tanzu network registry credentials. Mutually exclusive with tanzunet_username/password.'
              type: string
            ca_cert_data:
              type: string
              description: tbs registry ca certificate (used for self signed registry)
            descriptor_name:
              description: Name of descriptor to import (required for dependency updater feature)
              examples:
              - lite
              - full
              type: string
            descriptor_version:
              description: 'Optional: Version of descriptor to use during install. This will override the version installed by default.'
              type: string
            enable_automatic_dependency_updates:
              description: 'Optional: Allow automatic import of new dependency updates from Tanzunet'
              type: bool
        tap_gui:
          type: object
          additionalProperties: true
          properties: {}
          description: TAP GUI configuration
        learningcenter:
          type: object
          additionalProperties: true
          properties: {}
          description: Learning Center configuration
        scanning:
          type: object
          additionalProperties: true
          properties: {}
          description: Scan controller configuration
        convention_controller:
          type: object
          additionalProperties: true
          properties: {}
          description: Convention Controller configuration
        source_controller:
          type: object
          additionalProperties: true
          properties: {}
          description: Source Controller configuration
        tekton_pipelines:
          type: object
          additionalProperties: true
          properties: {}
          description: Tekton pipelines configuration
