---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tap.tanzu.vmware.com
spec:
  displayName: "TAP package"
  longDescription: ""
  shortDescription: ""
  providerName: "VMware"
  maintainers:
  - name: "Dmitriy Kalinin"
  supportDescription: "https://tanzu.vmware.com/support"