---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "learningcenter.tanzu.vmware.com.0.3.0"
spec:
  refName: "learningcenter.tanzu.vmware.com"
  version: "0.3.0"
  releasedAt: "2021-10-13T22:23:01Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  valuesSchema:
    openAPIv3:
      title: "learningcenter.tanzu.vmware.com values schema"
      examples:
      - ingressDomain: workshops.example.com
        namespace: educates
      properties:
        namespace:
          type: string
          description: The namespace in which to deploy Educates
          default: educates
        ingressDomain:
          type: string
          description: DNS parent subdomain used for training portal and workshop ingresses.
          default: workshops.example.com
          examples:
          - workshops.mydomain.com
          - 192.168.0.2.nip.io
        ingressClass:
          type: string
          description: Ingress class for where multiple ingress controllers exist and need to use that which is not marked as the default
        ingressSecret:
          type: object
          description: SSL certificate for secure ingress. Must be a wildcard certificate for children of DNS parent ingress subdomain
          properties:
            certificate:
              type: string
              description: Certificate - PEM format
            privateKey:
              type: string
              description: Private key - PEM format
            secretName:
              type: string
              description: If you already have a secret to use with a ingress resource, you can use this property to define it. (This property will take precedence over certificate and privateKey properties )
        storageClass:
          type: string
          description: Configuration for persistent volumes. The default storage class specified by the cluster will be used if not defined
        storageUser:
          type: string
          description: Storage group may need to be set where a cluster has pod security policies enabled, usually setting it to one. Storage user and storage group can be set in exceptional case where storage class used maps to NFS storage and storage server requires specific user and group always be used
        storageGroup:
          type: string
          description: Storage group may need to be set where a cluster has pod security policies enabled, usually setting it to one. Storage user and storage group can be set in exceptional case where storage class used maps to NFS storage and storage server requires specific user and group always be used
        portalCredentials:
          type: object
          description: Credentials for accessing training portal instances. If not specified then random passwords are generated which can be obtained from the custom resource for the training portal
          properties:
            systemAdmin:
              type: object
              properties:
                username:
                  type: string
                  default: educates
                password:
                  type: string
            clientAccess:
              type: object
              properties:
                username:
                  type: string
                  default: robot@educates
                password:
                  type: string
        imageRegistry:
          type: object
          description: Primary image registry where Educates container images are stored. It is only necessary to define the host and credentials when that image registry requires authentication to access images
          properties:
            host:
              description: Private registry domain
              type: string
            username:
              type: string
            password:
              type: string
        prepullImages:
          type: array
          description: Prepull images to nodes in cluster. Should be empty list if no images should be prepulled. Normally you would only want to prepull workshop images. This is done to reduce start up times for sessions
          items:
            type: string
          default: base-environment
          examples:
          - training-portal
          - docker-registry
          - dind-rootless
          - base-environment
          - jdk8-environment
          - jdk11-environment
          - conda-environment
        dockerDaemon:
          type: object
          properties:
            networkMTU:
              type: integer
              description: Docker daemon settings when building docker images in a workshop is enabled
              default: 1500
            proxyCache:
              type: object
              description: Proxy cache provides a way of partially getting around image pull limits for Docker Hub image registry, with the remote URL being set to "https://registry-1.docker.io
              properties:
                remoteURL:
                  type: integer
                username:
                  type: integer
                password:
                  type: integer
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "projects.registry.vmware.com/educates/educates-carvel:0.3.0"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - "kbld-bundle.yml"
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}