apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: default-supply-chain.tanzu.vmware.com.0.2.0
spec:
  refName: default-supply-chain.tanzu.vmware.com
  version: 0.2.0
  releaseNotes: |
    Default supply chain contents package
  valuesSchema:
    openAPIv3:
      title: default-supply-chain.tanzu.vmware.com values schema
      examples:
      - registry:
          server: https://gcr.io
          repository: tanzu_desktop
          username: user
          password: password
      properties:
        registry.server:
          type: string
          description: registry hostname
          default: https://gcr.io
          examples:
          - https://gcr.io
        registry.repository:
          type: string
          description: Registry repository
          default: tanzu_desktop
          examples:
          - tanzu_desktop
        registry.username:
          type: string
          description: Registry username
          default: ""
          examples:
          - stranger
        registry.password:
          type: string
          description: Registry password
          default: ""
          examples:
          - baddpass
        supplychain.imagerepository.secret:
          type: string
          description: Image repository secret
          default: ""
          examples:
          - reposecret
        supplychain.podintent.secret:
          type: string
          description: Image repository secret
          default: ""
          examples:
          - podintentsecret
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/default-supply-chain/default-supply-chain:0.2.0
      template:
      - ytt:
          paths:
          - config/
      deploy:
      - kapp: {}
