apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: default-supply-chain.tanzu.vmware.com.0.2.0
spec:
  refName: default-supply-chain.tanzu.vmware.com
  version: 0.2.0
  releaseNotes: |
    Default supply chain contents package
  valuesSchema:
    openAPIv3:
      title: default-supply-chain.tanzu.vmware.com values schema
      examples:
      - registry:
          server: https://youregistry.io
          repository: sample-repo
      properties:
        registry.server:
          type: string
          description: registry hostname
          default: https://yourregistry.io
          examples:
          - https://yourregistry.io
        registry.repository:
          type: string
          description: Registry repository
          default: sample-repo
          examples:
          - sample-repo
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/default-supply-chain/default-supply-chain@sha256:35dd6b5e67fec0df0e1294ff1bfc65c6ce55fdecb1917240cf0efe71edbd8666
      template:
      - ytt:
          paths:
          - config/
      deploy:
      - kapp: {}
