apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ootb-templates.tanzu.vmware.com.0.7.0-build.1
spec:
  refName: ootb-templates.tanzu.vmware.com
  version: 0.7.0-build.1
  releasedAt: "2022-03-03T23:32:22Z"
  valuesSchema:
    openAPIv3:
      title: ootb-templates
      properties:
        excluded_templates:
          type: array
          items:
            type: string
          default: []
          description: List of templates to exclude from the installation (e.g. ['git-writer'])
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:5a4cf069261f9010c5461d7956541eba400fcd0de8259404d36694dac32bc2db
      template:
      - ytt:
          ignoreUnknownComments: true
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
