#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/_profiles.star", "profiles")

#@ if data.values.install_flux and profiles.is_any_enabled([profiles.full, profiles.dev_light, profiles.operator_light]):

---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: flux-system

#@ def flux_updates():
#@overlay/match by=overlay.all,expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: flux-system

#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
      #@overlay/append
      - name: registry-creds

#@overlay/append
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: flux-system
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
#@ end

--- #@ template.replace(overlay.apply(library.get("upstream").eval(), flux_updates()))

#@ end
