apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: scp-toolkit.tanzu.vmware.com
spec:
  categories:
  - services
  displayName: SCP Toolkit
  longDescription: SCP Toolkit, featuring Service API Projection and Service Description.
  maintainers:
  - name: The Services Control Plane team
  providerName: VMware
  shortDescription: The SCP Toolkit
  supportDescription: https://tanzu.vmware.com/support
