---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "workshops.learningcenter.tanzu.vmware.com.0.2.0"
spec:
  refName: "workshops.learningcenter.tanzu.vmware.com"
  version: "0.2.0"
  releasedAt: "2022-03-03T00:38:29Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:cd38601896da00055e550c71f948de0ed1d69ac82f72d3d1ee4ae974447c50e5"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}