---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: accelerator.tanzu.vmware.com.0.1.0
spec:
  refName: accelerator.tanzu.vmware.com
  version: 0.1.0
  releaseNotes: |
        Release 0.1.0 of the App Accelerator package
  valuesSchema:
    openAPIv3:
      title: accelerator.tanzu.vmware.com values schema
      properties:
        server_service_type:
          type: string
          description: Type to use for the Service of the app.
          default: LoadBalancer
          examples:
          - NodePort
        server_watched_namespace:
          type: string
          description: Type to use for the Service of the app.
          default: "default"
        server_engine_invocation_url:
          type: string
          description: Type to use for the Service of the app.
          default: "http://acc-engine.accelerator-system.svc.cluster.local/invocations"
        engine_service_type:
          type: string
          description: Type to use for the Service of the app.
          default: "ClusterIP"
          examples:
          - NodePort
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.pivotal.io/app-accelerator/acc-install-bundle:0.1.0
          secretRef:
            name: target-registry-secret
      template:
      - ytt:
          paths:
          - "config"
          - "values.yml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
