---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: accelerator.tanzu.vmware.com.0.2.0-snapshot
spec:
  refName: accelerator.tanzu.vmware.com
  version: 0.2.0-snapshot
  releaseNotes: |
        Preview release of the App Accelerator package
  valuesSchema:
    openAPIv3:
      title: accelerator.tanzu.vmware.com values schema
      examples:
      - service_type: NodePort
      properties:
        service_type:
          type: string
          description: Type to use for the Service of the app.
          default: LoadBalancer
          examples:
          - NodePort
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.pivotal.io/app-accelerator/acc-install-bundle:0.2.0-snapshot
          secretRef:
            name: target-registry-secret
      template:
      - ytt:
          paths:
          - "config"
          - "values.yml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
