apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  # This will be the name of our package
  name: cnrs.tanzu.vmware.com
spec:
  displayName: "Cloud Native Runtimes"
  longDescription: "Cloud Native Runtimes for Tanzu is a serverless application runtime for Kubernetes that is based on Knative and runs on a single Kubernetes cluster"
  shortDescription: "Cloud Native Runtimes is a serverless runtime based on Knative"
