---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: connector.appliveview.tanzu.vmware.com.1.1.1-build.1
spec:
  refName: connector.appliveview.tanzu.vmware.com
  version: 1.1.1-build.1
  releaseNotes: |
        Release 1.1.1-build.1 of the App Live View Connector package
  releasedAt: 2022-04-19T00:00:10Z
  valuesSchema:
    openAPIv3:
      title: connector.appliveview.tanzu.vmware.com values schema
      properties:
        backend:
          type: object
          description: Backend Configuration
          properties:
            sslDisabled:
              description: Flag for whether or not to disable ssl
              type: boolean
              default: false
            host:
              type: string
              description: |
                Domain to be used to reach the application live view backend. Prepend "appliveview"
                subdomain to the value if you are using shared ingress. For example:
                "example.com" would become "appliveview.example.com".
            port:
              description: Port to reach the application live view backend
              type: number
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-connector-bundle@sha256:63ac55ad80dd203f1dccaeff2903d5c17e29332861a8d52d063b436c377ee8a7

      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
