---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: connector.appliveview.tanzu.vmware.com
spec:
  maintainers:
    - name : "Martin Lippert"
  providerName: "VMware"
  displayName: "Application Live View Connector for VMware Tanzu"
  longDescription: "Application Live View Connector discovers the application pods running on the Kubernetes cluster and register the instances to the Application Live View Server for it to be observed"
  shortDescription: "App for discovering and registering running apps"
  supportDescription: "https://tanzu.vmware.com/support"
