apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap.tanzu.vmware.com.0.4.0-build.12
spec:
  refName: tap.tanzu.vmware.com
  version: 0.4.0-build.12
  releaseNotes: |
    Beta release 0.4.0-build.12 of Tanzu Application Platform.
    This package allows to select which set of packages to install via profile data value.
  releasedAt: "2021-12-03T00:00:00Z"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/tap@sha256:5fa31c0edce8ca02269d6a94feec5ceefc7a35bdfd96afdfac9920e37ae28f50
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        profile:
          type: string
          default: full
          description: "Profile to install. Valid values: full, dev"
        supply_chain: 
          type: string
          default: basic
          description: "Supply chain to install. Valid values: basic, testing, testing_scanning"
        excluded_packages:
          type: array
          items:
            type: string
          default: []
          description: "List of packages to exclude from installation (e.g. [tap-gui.tanzu.vmware.com])"
        api_portal:
          type: object
          additionalProperties: true
          properties: {}
          description: "API Portal configuration"
        accelerator:
          type: object
          additionalProperties: true
          properties: {}
          description: "Accelerator configuration"
        appliveview:
          type: object
          additionalProperties: true
          properties: {}
          description: "App Live View configuration"
        cnrs:
          type: object
          additionalProperties: true
          description: "Cloud Native Runtimes configuration"
          properties: 
            ingress:
              type: object
              properties:
                reuse_crds:
                  type: boolean
                  description: "Optional: Only valid if a Contour instance already present in the cluster. Set to \"true\" if you want CNR to re-use the cluster's existing Contour CRDs."
                  default: true
                external:
                  type: object
                  properties:
                    namespace:
                      type: string
                      description: "Optional: Only valid if a Contour instance already present in the cluster. Specify a namespace where an existing Contour is installed on your cluster (for external services) if you want CNR to use your Contour instance."
                      default: tanzu-system-ingress
                internal:
                  type: object
                  properties:
                    namespace:
                      type: string
                      description: "Optional: Only valid if a Contour instance already present in the cluster. Specify a namespace where an existing Contour is installed on your cluster (for internal services) if you want CNR to use your Contour instance."
                      default: tanzu-system-ingress 
        ootb_supply_chain_basic:
          type: object
          additionalProperties: true
          properties: {}           
          description: "OOTB Supply Chain Basic configuration"
        ootb_supply_chain_testing:
          type: object
          additionalProperties: true
          properties: {}
          description: "OOTB Supply Chain Testing configuration"
        ootb_supply_chain_testing_scanning:
          type: object
          additionalProperties: true
          properties: {}
          description: "OOTB Supply Chain Testing Scanning configuration"
        image_policy_webhook:
          type: object
          additionalProperties: true
          properties: {}
          description: "Image Policy Webhook configuration"
        buildservice:
          type: object
          description: "Build Service configuration"
          properties:
            kp_default_repository:
              type: string
              description: docker repository (required)
              examples:
              - registry.io/build-service
            kp_default_repository_username:
              type: string
              description: registry username (required)
              examples:
              - janedoe@vmware.com
            kp_default_repository_password:
              type: string
              description: registry password (required)
              examples:
              - password
            tanzunet_username:
              type: string
              description: tanzunet registry username (required for dependency updater feature)
              examples:
              - janedoe@vmware.com
            tanzunet_password:
              type: string
              description: tanzunet registry password (required for dependency updater feature)
              examples:
              - password
            ca_cert_data:
              type: string
              description: tbs registry ca certificate (used for self signed registry)
        tap_gui:
          type: object
          additionalProperties: true
          properties: {}
          description: "TAP GUI configuration"
        learningcenter:
          type: object
          additionalProperties: true
          properties: {}
          description: "Learning Center configuration"
        scanning:
          type: object
          additionalProperties: true
          properties: {}
          description: "Scan controller configuration"
