apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: contour.tanzu.vmware.com
spec:
  displayName: contour
  shortDescription: An ingress controller
  longDescription: An Envoy-based ingress controller that supports dynamic configuration updates and multi-team ingress delegation. See https://projectcontour.io for more information.
  providerName: VMware
  maintainers:
  - name: Steve Kriss
  - name: Steve Sloka
  - name: Nick Young
  - name: Sunjay Bhatia
  - name: Nicholas Seemiller
  categories:
  - ingress