apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tekton.tanzu.vmware.com.0.29.0
spec:
  refName: tekton.tanzu.vmware.com
  version: 0.29.0
  releasedAt: "2021-10-19T14:02:27Z"
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tektoncd/bundle@sha256:1d6203fdaf10f5dec6ebc35d24bd29173d7c5adc9d5f15d3a8574d362d0fb4b7
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config.yml
      - ytt:
          inline:
            paths:
              secregen.yaml: |
                #@ load("@ytt:overlay", "overlay")
                ---
                apiVersion: v1
                kind: Secret
                metadata:
                  name:  private-registry-secret
                  namespace: tekton-pipelines
                  annotations:
                      secretgen.carvel.dev/image-pull-secret: ""
                type: kubernetes.io/dockerconfigjson
                data:
                  .dockerconfigjson: e30K

                #@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"namespace":"tekton-pipelines"}}),expects="2+"
                ---
                spec:
                  template:
                    spec:
                      #@overlay/match missing_ok=True
                      imagePullSecrets:
                      - name: private-registry-secret
          paths:
          - '-'
          - config.yml
      deploy:
      - kapp: {}
