---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "workshops.learningcenter.tanzu.vmware.com.0.2.0"
spec:
  refName: "workshops.learningcenter.tanzu.vmware.com"
  version: "0.2.0"
  releasedAt: "2022-03-16T21:15:05Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:2522df0c6957dd1ac82ba6ec9d295f7af906637c95abab6a069cb2a81fed7b8e"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}