---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "workshops.learningcenter.tanzu.vmware.com.0.2.1"
spec:
  refName: "workshops.learningcenter.tanzu.vmware.com"
  version: "0.2.1"
  releasedAt: "2022-05-17T16:16:02Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:de4df29a28aa6001c1df26177dde9041571b9349c55e586758f21aa39cdf3888"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}