apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: default-supply-chain-testing.apps.tanzu.vmware.com
spec:
  displayName: Tanzu App Platform Default Supply Chain with Testing
  shortDescription: A default Supply Chain with testing
  longDescription: |-
    Tanzu App Platform Default Supply Chain with Testing powers workloads that
    require running tests.
  providerName: VMware
