---
namespaces:
  - tap-install
  - my-apps
outerloop:
  catalog_info_yaml: https://github.com/dapdelivery/tap-catalog/blob/master/catalog-info.yaml
  mysql:
    name: mysql-db
    namespace: my-apps
    yaml_file: mysql-service.yaml
  namespace: my-apps
  project:
    repository: https://github.com/dapdelivery/spring-petclinic.git
    name: spring-petclinic
    file: src/main/resources/templates/fragments/layout.html
    original_string: "PetClinic :: a Spring Framework demonstration"
    new_string: "Spring PetClinic :: a Spring Framework demonstration"
    application: spring-petclinic.my-apps.example.com
  scan_policy:
    namespace: my-apps
    yaml_file: scan-policy.yaml
  spring_petclinic:
    build_name_prefix: spring-petclinic
    gitrepository_name: spring-petclinic
    imagerepository_name: spring-petclinic-delivery
    ksvc_name: spring-petclinic
    name: spring-petclinic-tests-pipeline
    namespace: my-apps
    podintent_name: spring-petclinic
    taskrun_name_prefix: spring-petclinic-config-writer
    yaml_file: spring-petclinic-tests-pipeline.yaml
  workload:
    namespace: my-apps
    yaml_file: workload.yaml
innerloop:
  workload:
    namespace: tap-install
    name: tanzu-java-web-app
    url: "tanzu-java-web-app.tap-install.example.com"
package_repository:
  image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:1.0.1-build.2
  name: tanzu-tap-repository
  namespace: tap-install
tanzunet_creds_secret:
  export: true
  name: tanzunet-registry-creds
  namespace: tap-install
  password: <TANZUNET-PASSWORD>
  registry: registry.tanzu.vmware.com
  username: <TANZUNET-USERNAME>
image_secret:
  export: false
  name: image-secret
  namespace: my-apps
  password: <REGISTRY-PASSWORD>
  registry: <REGISTRY>
  username: <REGISTRY-USERNAME>
tap:
  name: tap
  namespace: tap-install
  package_name: tap.tanzu.vmware.com
  poll_timeout: 45m
  values_schema_file: tap-values.yaml
  version: 1.0.1-build.2
tanzu-cluster-essentials:
  bundle: registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:82dfaf70656b54dcba0d4def85ccae1578ff27054e7533d08320244af7fb0343
  registry: registry.tanzu.vmware.com
  filename: install.sh