apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer.tanzu.vmware.com.0.3.0-build.3
spec:
  refName: cartographer.tanzu.vmware.com
  version: 0.3.0-build.3
  releaseNotes: https://github.com/vmware-tanzu/cartographer/releases/tag/0.3.0-build.3
  releasedAt: "2022-03-16T17:05:45Z"
  valuesSchema:
    openAPIv3:
      title: cartographer.tanzu.vmware.com.0.3.0-build.3 values schema
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/supply-chain-choreographer/cartographer@sha256:4e8974f50b7cc713e810bee544d554b9f406769a8a154f7a3f596a0302785cf5
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - config
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
