---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: spring-boot-conventions.tanzu.vmware.com.0.2.0
spec:
  refName: spring-boot-conventions.tanzu.vmware.com
  version: 0.2.0
  releasedAt: 2021-11-22T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-spring-boot-convention/spring-boot-conventions@sha256:d521ae4633b6f1e405fa43edd0dc523c62a3209cd6aefc98e0aab6c7d2bf8fc7
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - spring-boot-convention-server/server.yaml
      - ytt:
          paths:
          - '-'
          - spring-boot-convention-server/bundle.yaml
      deploy:
      - kapp: {}