apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ootb-templates.tanzu.vmware.com.0.3.0-build.4
spec:
  refName: ootb-templates.tanzu.vmware.com
  version: 0.3.0-build.4
  releasedAt: "2021-10-29T20:35:45Z"
  valuesSchema:
    openAPIv3:
      title: ootb-templates
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:3922862dfd79d9428256f033d9a8390a72a97d14b52798b5ac951e8cf560786f
      template:
      - ytt:
          ignoreUnknownComments: true
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
