#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")

#@ if data.values.install_cert_manager:

#@ def cert_mgr_updates():
#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      imagePullSecrets:
      #@overlay/append
      - name: registry-creds
#@overlay/append
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-creds
  namespace: cert-manager
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
#@ end

--- #@ template.replace(overlay.apply(library.get("upstream").eval(), cert_mgr_updates()))

#@overlay/match by=overlay.subset({"metadata": {"labels": {"app.kubernetes.io/instance": "cert-manager"}}}),expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-group.certmgr: "cert-manager"

#! some packages depends on cert-manager and add webhooks
#! which in turn may block deployment of cert-manager itself
#@overlay/match by=overlay.subset({"kind": "PackageInstall"}),expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/change-rule.certmgr: "upsert after upserting cert-manager"

#@ end
