apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: services-toolkit.tanzu.vmware.com.0.6.0
spec:
  refName: services-toolkit.tanzu.vmware.com
  version: 0.6.0
  releaseNotes: https://docs.vmware.com/en/Services-Toolkit-for-VMware-Tanzu/0.6/services-toolkit-0-6/GUID-overview.html
  releasedAt: "2022-04-12T00:00:00Z"
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/scp-toolkit/scp-toolkit-package-bundle@sha256:3f4960619a7b84041dae6fda4925bfbff3d5dabf3e4645c5aee27857f7ee0271
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - kbld.yaml
          - .imgpkg/images.yml
