---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: appliveview.tanzu.vmware.com.1.0.0-build.2
spec:
  refName: appliveview.tanzu.vmware.com
  version: 1.0.0-build.2
  releaseNotes: |
        Release 1.0.0-build.2 of the App Live View package
  releasedAt: 2021-11-29T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-install-bundle@sha256:60a01776ef8c63cbba0441e8e6493277aea353f2bbd16280ae6bc922fca6a4d4
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
