---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: controller.conventions.apps.tanzu.vmware.com.0.6.3
spec:
  refName: controller.conventions.apps.tanzu.vmware.com
  version: 0.6.3
  releasedAt: 2022-03-08T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties:
        ca_cert_data:
          type: string
          description: "Optional: PEM Encoded certificate data for image registries with private CA."
          default: ""
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-convention-service/convention-controller-bundle@sha256:2d3b5e53ed294e3f7ce64294dd6db0f50aef78ff8b1fdd1b02b513fd5aa0d23f
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/namespace.yaml
          - config/convention-controller.yaml
      - ytt:
          paths:
          - "-"
          - bundle.yaml
      deploy:
      - kapp: {}
