kp_default_repository: <KP-DEFAULT-REPOSITORY>
kp_default_repository_password: <KP-DEFAULT-REPOSITORY-PASSWORD>
kp_default_repository_username: <KP-DEFAULT-REPOSITORY-USERNAME>
tanzunet_password: <TANZUNET-PASSWORD>
tanzunet_username: <TANZUNET-USERNAME>
descriptor_name: tap-1.0.0-lite