apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-telemetry.tanzu.vmware.com.0.1.4
spec:
  refName: tap-telemetry.tanzu.vmware.com
  version: 0.1.4
  releasedAt: "2021-11-30T00:00:00Z"
  releaseNotes: Initial release of tap-telemetry.
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-telemetry/telemetry-bundle@sha256:64139ce3b28af09b8e3a5459ff07be55781802ba1a58b5f5968702981e702b0a
      template:
      - ytt:
          paths:
          - config.yaml
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
