---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package:1.0.4
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 1.0.4
          url: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package:1.0.4
  image: dev.registry.tanzu.vmware.com/api-portal/api-portal-carvel-package@sha256:2196ce8b828205e9f403a4094722671f283223b3ee8b7f8841fea9a3557c8316
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/app-accelerator/acc-install-bundle:0.4.0
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 0.4.0
          url: dev.registry.tanzu.vmware.com/app-accelerator/acc-install-bundle:0.4.0
  image: dev.registry.tanzu.vmware.com/app-accelerator/acc-install-bundle@sha256:e3af6fbbbce1defd461e9d7e2800bca44ec98e5901c4cd1ea428cf9acc9c7616
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-install-bundle@sha256:05e673e2cc0c5135bb6a06a2f8e7dc2107a289ce9bfebe4384082c5fde0dc543
  image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-install-bundle@sha256:05e673e2cc0c5135bb6a06a2f8e7dc2107a289ce9bfebe4384082c5fde0dc543
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/build-service/bundle@sha256:33f933df5cb5251a7286b321118827781c74d5f1359e2fc8715f7f80fa892bef
  image: dev.registry.tanzu.vmware.com/build-service/bundle@sha256:33f933df5cb5251a7286b321118827781c74d5f1359e2fc8715f7f80fa892bef
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/developer-conventions/developer-conventions-bundle:0.4.0-build1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 0.4.0-build1
          url: dev.registry.tanzu.vmware.com/developer-conventions/developer-conventions-bundle:0.4.0-build1
  image: dev.registry.tanzu.vmware.com/developer-conventions/developer-conventions-bundle@sha256:03cce2af263da5d8ee6a2064831ea0635f24cefd98ae1c20a0eba23e47ad841e
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/fluxcd-source-controller/fluxcd-source-controller-bundle@sha256:3e90cb4294f8bf03007ba6fe9b5f30ed28ea506e1c225ac72a32601e82b8d988
  image: dev.registry.tanzu.vmware.com/fluxcd-source-controller/fluxcd-source-controller-bundle@sha256:3e90cb4294f8bf03007ba6fe9b5f30ed28ea506e1c225ac72a32601e82b8d988
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/learning-center/learning-center-package@sha256:c5b29f394753a920ffb1bf9a2285f02181167ad93af0395cbefbd0cc79dc1a7d
  image: dev.registry.tanzu.vmware.com/learning-center/learning-center-package@sha256:c5b29f394753a920ffb1bf9a2285f02181167ad93af0395cbefbd0cc79dc1a7d
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:bc866f95990c7eab41b61dcb53cf3eab2912ea203eb422b600dd14e9bc355a41
  image: dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:bc866f95990c7eab41b61dcb53cf3eab2912ea203eb422b600dd14e9bc355a41
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/ootb-supply-chain-basic/ootb-supply-chain-basic@sha256:d8f3ddd7475bb9ba7a550ee10ce8aba82ae3e1f15db178bc7c616967ed2e2f88
  image: dev.registry.tanzu.vmware.com/ootb-supply-chain-basic/ootb-supply-chain-basic@sha256:d8f3ddd7475bb9ba7a550ee10ce8aba82ae3e1f15db178bc7c616967ed2e2f88
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/ootb-supply-chain-testing-scanning/ootb-supply-chain-testing-scanning@sha256:7805db5d6bac433f6739c82f03c5e88457081ac84f58136321612f32554b0b2a
  image: dev.registry.tanzu.vmware.com/ootb-supply-chain-testing-scanning/ootb-supply-chain-testing-scanning@sha256:7805db5d6bac433f6739c82f03c5e88457081ac84f58136321612f32554b0b2a
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/ootb-supply-chain-testing/ootb-supply-chain-testing@sha256:6921bdb9eb1bc547676072f12842ebc994ed3340f422e1e21da7f5228f5dd9c1
  image: dev.registry.tanzu.vmware.com/ootb-supply-chain-testing/ootb-supply-chain-testing@sha256:6921bdb9eb1bc547676072f12842ebc994ed3340f422e1e21da7f5228f5dd9c1
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:ed0606dcbabb0e2864cfab84ddefd0222cbf4a952d7dea998969a8e596960aa3
  image: dev.registry.tanzu.vmware.com/ootb-templates/ootb-templates@sha256:ed0606dcbabb0e2864cfab84ddefd0222cbf4a952d7dea998969a8e596960aa3
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/scp-toolkit/scp-toolkit@sha256:16fdd9fc8f04c78f148724bd75c8e08ea3f261d24a01a9d06dbe48ad09c98d90
  image: dev.registry.tanzu.vmware.com/scp-toolkit/scp-toolkit@sha256:16fdd9fc8f04c78f148724bd75c8e08ea3f261d24a01a9d06dbe48ad09c98d90
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/serverless/1.0.3-build.112.tap.beta.3@sha256:8f4249416705dd7221073677210c251bf72ba7c1bbec788e77785443cd88c37b
  image: dev.registry.tanzu.vmware.com/serverless/1.0.3-build.112.tap.beta.3@sha256:8f4249416705dd7221073677210c251bf72ba7c1bbec788e77785443cd88c37b
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/service-bindings-for-kubernetes/service-bindings-bundle@sha256:e8f52ce61238d3b3f16f0ce0a2f1ae13a4e62e97f0c948457de83025760b66a6
  image: dev.registry.tanzu.vmware.com/service-bindings-for-kubernetes/service-bindings-bundle@sha256:e8f52ce61238d3b3f16f0ce0a2f1ae13a4e62e97f0c948457de83025760b66a6
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/supply-chain-choreographer/cartographer@sha256:35bfc11d92c14446863e251ad659a7232825212229d529a40d28c468c70392ec
  image: dev.registry.tanzu.vmware.com/supply-chain-choreographer/cartographer@sha256:35bfc11d92c14446863e251ad659a7232825212229d529a40d28c468c70392ec
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/supply-chain-security-tools/grype-templates:v1.0.0-beta.2.build.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.0.0-beta.2.build.1
          url: dev.registry.tanzu.vmware.com/supply-chain-security-tools/grype-templates:v1.0.0-beta.2.build.1
  image: dev.registry.tanzu.vmware.com/supply-chain-security-tools/grype-templates@sha256:0a241843322296b4a4c363fbe2a1762248718179cc377182db20c7f49ce8837b
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/supply-chain-security-tools/image-policy-webhook-bundle:1.0.0-beta.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 1.0.0-beta.1
          url: dev.registry.tanzu.vmware.com/supply-chain-security-tools/image-policy-webhook-bundle:1.0.0-beta.1
  image: dev.registry.tanzu.vmware.com/supply-chain-security-tools/image-policy-webhook-bundle@sha256:dbd55127d35c8634cb27bdffc2d5e1574b660ddbb032926d00822e9881ca30c6
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/supply-chain-security-tools/insight-metadata-store-bundle@sha256:61e88ca1d380bd65e330318a8f4525178876184981683dd2d524294066f15a37
  image: dev.registry.tanzu.vmware.com/supply-chain-security-tools/insight-metadata-store-bundle@sha256:61e88ca1d380bd65e330318a8f4525178876184981683dd2d524294066f15a37
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/supply-chain-security-tools/scan-controller:v1.0.0-beta.2.build.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.0.0-beta.2.build.1
          url: dev.registry.tanzu.vmware.com/supply-chain-security-tools/scan-controller:v1.0.0-beta.2.build.1
  image: dev.registry.tanzu.vmware.com/supply-chain-security-tools/scan-controller@sha256:857593f931f603c0d94d74bbe80e2337ce0dd3eb867c8b975dd717b51737ab4d
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tanzu-application-platform/cert-manager-pkg:v1.5.3_vmware.2-tkg.1-20211114
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.5.3_vmware.2-tkg.1-20211114
          url: dev.registry.tanzu.vmware.com/tanzu-application-platform/cert-manager-pkg:v1.5.3_vmware.2-tkg.1-20211114
  image: dev.registry.tanzu.vmware.com/tanzu-application-platform/cert-manager-pkg@sha256:e4b2967b7b0779dc363ca0411fa098e251ba4c1fcd97cf1b976ea71b23aee2c4
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tanzu-application-platform/contour-pkg:v1.18.2_vmware.1-tkg.1-20211114
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v1.18.2_vmware.1-tkg.1-20211114
          url: dev.registry.tanzu.vmware.com/tanzu-application-platform/contour-pkg:v1.18.2_vmware.1-tkg.1-20211114
  image: dev.registry.tanzu.vmware.com/tanzu-application-platform/contour-pkg@sha256:0fa15087a20bf738567766d5faf237af928daa975822c581dbdfffb8d29fdf19
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tanzu-application-platform/tap@sha256:944ddccaefc6adf6168402b335cd9e5ed2bac8cca715f84f3ac65fbbdd0f8cda
  image: dev.registry.tanzu.vmware.com/tanzu-application-platform/tap@sha256:944ddccaefc6adf6168402b335cd9e5ed2bac8cca715f84f3ac65fbbdd0f8cda
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tanzu-convention-service/convention-controller-bundle@sha256:fcf95067b792e8a043cc51638fcd0001875d2895bf09349b34a9d2b0056850a1
  image: dev.registry.tanzu.vmware.com/tanzu-convention-service/convention-controller-bundle@sha256:fcf95067b792e8a043cc51638fcd0001875d2895bf09349b34a9d2b0056850a1
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tanzu-source-controller/source-controller-bundle@sha256:d4e9bca1c7520346dbc26087e8470380fd5339e4b3c3bf97d8e64bb58efc4c2c
  image: dev.registry.tanzu.vmware.com/tanzu-source-controller/source-controller-bundle@sha256:d4e9bca1c7520346dbc26087e8470380fd5339e4b3c3bf97d8e64bb58efc4c2c
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tanzu-spring-boot-convention/spring-boot-conventions@sha256:d521ae4633b6f1e405fa43edd0dc523c62a3209cd6aefc98e0aab6c7d2bf8fc7
  image: dev.registry.tanzu.vmware.com/tanzu-spring-boot-convention/spring-boot-conventions@sha256:d521ae4633b6f1e405fa43edd0dc523c62a3209cd6aefc98e0aab6c7d2bf8fc7
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tap-gui/bundle:0.3.0
    kbld.carvel.dev/origins: |
      - resolved:
          tag: 0.3.0
          url: dev.registry.tanzu.vmware.com/tap-gui/bundle:0.3.0
  image: dev.registry.tanzu.vmware.com/tap-gui/bundle@sha256:47711771c39fc6c14561738791b86e0eecc4a5c3d66a7e55339b99b0786640e3
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/tektoncd/bundle@sha256:9c15da57a699bd50e89988de0db343b55d67ce587bd1e1e36183516e1698e8cf
  image: dev.registry.tanzu.vmware.com/tektoncd/bundle@sha256:9c15da57a699bd50e89988de0db343b55d67ce587bd1e1e36183516e1698e8cf
kind: ImagesLock
