apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cartographer.carto.run.0.0.8
  annotations:
    kapp.k14s.io/change-group: carto.run/meta
spec:
  refName: cartographer.carto.run
  version: 0.0.8
  releaseNotes: https://github.com/vmware-tanzu/cartographer/releases/tag/0.0.8
  releasedAt: "2021-11-29T21:32:43Z"
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/supply-chain-choreographer/cartographer@sha256:34c7041b7244f76f23a716cf677bb7a709c986b26c7778046ef6f9b8e2a4c891
      template:
      - ytt:
          ignoreUnknownComments: true
          inline:
            paths:
              namespace.yaml: |-
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: cartographer-system
      - kbld: {}
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
