---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: build.appliveview.tanzu.vmware.com.1.0.0
spec:
  refName: build.appliveview.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: |
        Release 1.0.0 of the App Live View Conventions package
  releasedAt: 2021-12-06T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-conventions-bundle@sha256:207b03cc15d0526306664df41dcbc6d852df2a4128d3a67a83e0f27ca009c861
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}