apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluxcd.source.controller.tanzu.vmware.com.0.16.0
spec:
  refName: fluxcd.source.controller.tanzu.vmware.com
  version: 0.16.0
  releasedAt: "2021-10-08T10:30:14Z"
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/fluxcd-source-controller/fluxcd-source-controller-bundle@sha256:7a40f7e9eb16f9633d909d85979ab26714389e866c3fa37882e5c71ef99285c0
      template:
      - ytt:
          inline:
            paths:
              secretgen.yaml: |
                #@ load("@ytt:overlay", "overlay")
                ---
                apiVersion: v1
                kind: Secret
                metadata:
                  name: canonical-registry-secret
                  namespace: flux-system
                  annotations:
                    secretgen.carvel.dev/image-pull-secret: ""
                type: kubernetes.io/dockerconfigjson
                data:
                  .dockerconfigjson: e30K
                ---
                #@overlay/match by=overlay.subset({"kind":"Deployment","metadata":{"name":"source-controller"}}),expects="1+"
                ---
                spec:
                  template:
                    spec:
                      #@overlay/match missing_ok=True
                      imagePullSecrets:
                      - name: canonical-registry-secret
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
