namespace: tap-install
secrets:
  - name: tap-registry
    registry: registry.tanzu.vmware.com
    username: # TANZUNET_USERNAME
    password: # TANZUNET_PASSWORD
package_repository:
  name: tanzu-tap-repository
  image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages:0.2.0
packages:
  ## INDEPENDENT PACKAGES:
  - name: accelerator.apps.tanzu.vmware.com
    installed_name: app-accelerator
    version: 0.3.0
    use_values_file: app-accelerator.yaml
  - name: api-portal.tanzu.vmware.com
    installed_name: api-portal
    version: 1.0.2
  - name: cnrs.tanzu.vmware.com
    installed_name: cloud-native-runtimes
    version: 1.0.2
    use_values_file: cloud-native-runtimes.yaml
  - name: controller.source.apps.tanzu.vmware.com
    installed_name: source-controller
    version: 0.1.2
  - name: scp-toolkit.tanzu.vmware.com
    installed_name: scp-toolkit
    version: 0.3.0
  - name: service-bindings.labs.vmware.com
    installed_name: service-bindings
    version: 0.5.0
  - name: buildservice.tanzu.vmware.com
    installed_name: tanzu-build-service
    version: 1.3.0
    use_values_file: tanzu-build-service.yaml

  ## DEPENDENT PACKAGES:
  ### app-live-view requires convention-controller; developer-conventions requires app-live-view
  - name: controller.conventions.apps.tanzu.vmware.com
    installed_name: convention-controller
    version: 0.4.2
  - name: appliveview.tanzu.vmware.com
    installed_name: app-live-view
    version: 0.2.0
    use_values_file: app-live-view.yaml
  - name: developer-conventions.tanzu.vmware.com
    installed_name: developer-conventions
    version: 0.2.0
  ### default-supply-chain-testing requires cartographer; default-supply-chain requires cartographer
  ### NOTE: install only one of default-supply-chain-testing and default-supply-chain
  - name: cartographer.tanzu.vmware.com
    installed_name: cartographer
    version: 0.0.6
  - name: default-supply-chain-testing.tanzu.vmware.com
    installed_name: default-supply-chain-testing
    version: 0.2.0
    use_values_file: default-supply-chain.yaml
  - name: default-supply-chain.tanzu.vmware.com
    installed_name: default-supply-chain
    version: 0.2.0
    use_values_file: default-supply-chain.yaml
  ### image-policy-webhook requires metadata-store
  - name: scst-store.tanzu.vmware.com
    installed_name: metadata-store
    version: 1.0.0-beta.0
    use_values_file: scst-store.yaml
  - name: image-policy-webhook.signing.run.tanzu.vmware.com
    installed_name: image-policy-webhook
    version: 1.0.0-beta.0
    use_values_file: scst-sign.yaml
  ### scan-controller requires metadata-store; grype-scanner requires scan-controller
  - name: scanning.apps.tanzu.vmware.com
    installed_name: scan-controller
    version: 1.0.0-beta
    use_values_file: scst-scan-controller.yaml
  - name: grype.scanning.apps.tanzu.vmware.com
    installed_name: grype-scanner
    version: 1.0.0-beta
