---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: conventions.appliveview.tanzu.vmware.com.1.1.1-build.1
spec:
  refName: conventions.appliveview.tanzu.vmware.com
  version: 1.1.1-build.1
  releaseNotes: |
        Release 1.1.1-build.1 of the App Live View Conventions package
  releasedAt: 2022-04-19T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-conventions-bundle@sha256:fdd0e5563fde5fadd1a08c330055fddae9f98ee124c1be271daef1ba0342c9a2
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
