---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: conventions.appliveview.tanzu.vmware.com.1.1.2
spec:
  refName: conventions.appliveview.tanzu.vmware.com
  version: 1.1.2
  releaseNotes: |
        Release 1.1.2 of the App Live View Conventions package
  releasedAt: 2022-05-25T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/app-live-view/application-live-view-conventions-bundle@sha256:fde2115ba42ed610853413f1702aaa37f1e484fa1a92d5ef1e2c6f8f67589bb3
      template:
      - ytt:
          paths:
          - "config"
          - "values.yaml"
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
