---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: buildservice.tanzu.vmware.com.1.3.0
spec:
  refName: buildservice.tanzu.vmware.com
  version: 1.3.0
  releasedAt: "2021-09-28T00:00:00Z"
  capacityRequirementsDescription: Cluster with nodes > 50GB ephemeral storage, Registry > 5GB available space
  releaseNotes: https://docs.pivotal.io/build-service/1-3/release-notes.html
  valuesSchema:
    openAPIv3:
      title: buildservice.tanzu.vmware.com values schema
      properties:
        kp_default_repository:
          type: string
          description: docker repository (required)
          examples:
          - registry.io/build-service
        kp_default_repository_username:
          type: string
          description: registry username (required)
          examples:
          - janedoe@vmware.com
        kp_default_repository_password:
          type: string
          description: registry password (required)
          examples:
          - password
        tanzunet_username:
          type: string
          description: tanzunet registry username (required for dependency updater feature)
          examples:
          - janedoe@vmware.com
        tanzunet_password:
          type: string
          description: tanzunet registry password (required for dependency updater feature)
          examples:
          - password
        ca_cert_data:
          type: string
          description: tbs registry ca certificate (used for self signed registry)
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: registry.tanzu.vmware.com/build-service/bundle:1.3.0
      template:
      - ytt:
          paths:
          - values.yaml
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
