apiVersion: v1
kind: Secret
metadata:
  name: git-ssh # `git-ssh` is the default name.
                  #   - operators can change the default using `gitops.ssh_secret`.
                  #   - developers can override using `gitops_ssh_secret`
  annotations:
    tekton.dev/git-0: github.com  # git server host   (!! required)
type: kubernetes.io/ssh-auth
data:
  identity: <gitops-private-key>
  identity.pub: <gitops-public-key>
  known_hosts: <gitops-known-hosts>
  ssh-privatekey: <gitops-private-key>