---
catalog_info_yaml: https://github.com/dapdelivery/tap-catalog/blob/master/catalog-info.yaml
mysql:
  yaml_file: mysql-service.yaml
namespace: my-apps
project:
  host: spring-petclinic.my-apps.example.com
  webpage_relative_path: vets.html
  file: src/main/resources/templates/vets/vetList.html
  repo_template: spring-petclinic-template
  dest_repo_template: spring-petclinic-dest-template
  name: <GITHUB_REPO_NAME>
  dest_name: <GITHUB_DEST_REPO_NAME>
  new_string: "Validation checks at VMWare!!!"
  original_string: "Veterinarians"
  commit_message: "update vets.html: new header"
  repository: https://github.com/dapdelivery/<GITHUB_REPO_NAME>.git
  username: dapdelivery
  email: svc.dapdelivery@gmail.com
  access_token: <ACCESS_TOKEN>
scan_policy:
  yaml_file: scan-policy.yaml
spring_petclinic_pipeline:
  yaml_file: spring-petclinic-tests-pipeline.yaml
workload:
  name: spring-petclinic
  yaml_file: workload.yaml
  test_yaml_file: workload-test.yaml
  taskrun_name_infix: -config-writer-
  taskrun_test_suffix: -test
  pipeline_name: developer-defined-tekton-pipeline
  build_name_suffix: -build-1
  service_binding_suffix: -db
  gitops_yaml_file: workload-gitops.yaml
  gitssh_secret_yaml_file: git-ssh-secrets.yaml
buildpacks:
  scan_policy: lenient-scan-policy.yaml
  pipeline_yaml_file: pipeline-buildpacks-test.yaml
  workloads:
  - name: tanzu-java-web-app
    git_repository: https://github.com/dapdelivery/tanzu-java-web-app.git
    contains_conventions : true
  # - name: java-native-image-app
  #   git_repository: https://github.com/dapdelivery/test-buildpack-java-native-image-sample.git
  #   webpage_relative_path: actuator/health
  #   contains_conventions : true
  - name: python-pip-app
    git_repository: https://github.com/dapdelivery/test-buildpack-python-pip.git
  - name: dotnet-aspnet-app
    git_repository: https://github.com/dapdelivery/test-buildpack-dotnet-aspnet.git
  - name: go-dep-app
    git_repository: https://github.com/dapdelivery/test-buildpack-go-dep.git
  - name: nodejs-app
    git_repository: https://github.com/dapdelivery/test-buildpack-nodejs-sample.git
  
  # - name: ruby-rake-app
  #   git_repository: https://github.com/dapdelivery/test-buildpack-ruby-rake.git
  #   git_branch:
  #   webpage_relative_path: 
  
  # - name: php-composer-app
  #   git_repository: https://github.com/dapdelivery/test-buildpack-php-composer.git
  #   git_branch:
  #   webpage_relative_path: 
  
  # - name: nginx-sample-app
  #   git_repository: https://github.com/dapdelivery/test-buildpack-nginx-sample.git
  #   git_branch:
  #   webpage_relative_path: 

  # - name: httpd-sample-app
  #   git_repository: https://github.com/dapdelivery/test-buildpack-httpd-sample.git
  #   git_branch:
  #   webpage_relative_path: 

  # - name: git-sample-app
  #   git_repository: https://github.com/dapdelivery/test-buildpack-git-sample.git
  #   git_branch:
  #   webpage_relative_path: 