---
catalog_info_yaml: https://github.com/dapdelivery/tap-catalog/blob/master/catalog-info.yaml
mysql:
  yaml_file: mysql-service.yaml
namespace: my-apps
project:
  host: spring-petclinic.my-apps.example.com
  webpage_relative_path: vets.html
  file: src/main/resources/templates/vets/vetList.html
  repo_template: spring-petclinic-template
  name: <GITHUB_REPO_NAME>
  new_string: "Validation checks at VMWare!!!"
  original_string: "Veterinarians"
  commit_message: "update vets.html: new header"
  repository: https://github.com/dapdelivery/<GITHUB_REPO_NAME>.git
  username: dapdelivery
  email: svc.dapdelivery@gmail.com
  access_token: <ACCESS_TOKEN>
scan_policy:
  yaml_file: scan-policy.yaml
spring_petclinic_pipeline:
  yaml_file: spring-petclinic-tests-pipeline.yaml
workload:
  name: spring-petclinic
  yaml_file: workload.yaml
  test_yaml_file: workload-test.yaml
  taskrun_name_infix: -config-writer-
  taskrun_test_suffix: -test
  pipeline_name: developer-defined-tekton-pipeline
  build_name_suffix: -build-1
  service_binding_suffix: -db
  gitops_yaml_file: workload-gitops.yaml
  gitssh_secret_yaml_file: git-ssh-secrets.yaml
