---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: controller.conventions.apps.tanzu.vmware.com.0.5.1
spec:
  refName: controller.conventions.apps.tanzu.vmware.com
  version: 0.5.1
  releasedAt: 2022-02-17T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-convention-service/convention-controller-bundle@sha256:eba78cfe2a835a0560a944c071ab910928851ca1527d81441e1cc032a1e1bd82
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/namespace.yaml
          - config/convention-controller.yaml
      - ytt:
          paths:
          - "-"
          - bundle.yaml
      deploy:
      - kapp: {}
