---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: controller.conventions.apps.tanzu.vmware.com
spec:
  displayName: "Convention Service for VMware Tanzu"
  longDescription: "Convention Service enables app operators to consistently apply desired runtime configurations to fleets of workloads as they are deployed to the Tanzu platform"
  shortDescription: "Convention Service enables app operators to consistently apply desired runtime configurations to fleets of workloads."
  providerName: "VMware"
  maintainers:
  - name: "Scott Andrews"
  - name: "Rashed Kamal"
  supportDescription: "https://tanzu.vmware.com/support"
