---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: spring-boot-conventions.tanzu.vmware.com.0.1.1
spec:
  refName: spring-boot-conventions.tanzu.vmware.com
  version: 0.1.1
  releasedAt: 2021-10-25T00:00:00Z
  valuesSchema:
    openAPIv3:
      properties: {}
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-spring-boot-convention/spring-boot-conventions@sha256:28995bfb0ee323f738e7612f28e278d0b89f174019feccc60ee58132f7d30b76
      template:
      - ytt:
          paths:
          - spring-boot-convention-server/bundle.yaml
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
          - spring-boot-convention-server/server.yaml
      deploy:
      - kapp: {}