---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: "workshops.learningcenter.tanzu.vmware.com.0.1.0-build.7"
spec:
  refName: "workshops.learningcenter.tanzu.vmware.com"
  version: "0.1.0-build.7"
  releasedAt: "2021-12-01T13:18:48Z"
  licenses: 
  - "VMware’s End User License Agreement (Underlying OSS license: Apache License 2.0)"
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: "dev.registry.tanzu.vmware.com/learning-center/workshops-package@sha256:72830119ba882dde541502384c5edac3aa7f5806ab325bf8235b12b0b7860642"
      template:
      - ytt:
          paths:
          - "config/"
      - kbld:
          paths:
          - ".imgpkg/images.yml"
          - "-"
      deploy:
      - kapp: {}