apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: cert-manager.tanzu.vmware.com
spec:
  displayName: cert-manager
  longDescription: Provides certificate management provisioning within the cluster
  shortDescription: Certificate management
  providerName: VMware
  maintainers:
  - name: Nicholas Seemiller
  categories:
  - certificate management
