---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  labels: {}
  name: cnrs.tanzu.vmware.com.1.2.0
spec:
  capacityRequirementsDescription: Cluster with one node requires >6 CPUs, >6.0GB
    RAM, >30GB storage. Cluster with multiple nodes requires >2 CPUs, >4.0GB RAM,
    >20GB storage for each node.
  refName: cnrs.tanzu.vmware.com
  releasedAt: 2022-03-16T00:00:00Z
  releaseNotes: |
    Release 1.2.0 of the Cloud Native Runtimes app package
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/serverless/1.2.0-build.21@sha256:5a6d6e0dcbc8ccfe3177d41c8de191787b96567ac7ec4880fa39e3108c13d595
      template:
      - kbld:
          paths:
          - .imgpkg/images.yml
          - config/kbld.yaml
          - config/serving
          - config/net-contour
          - config/eventing
          - config/net-certmanager
          - config/aws-event-sources
      - ytt:
          ignoreUnknownComments: true
          paths:
          - '-'
          - config/ytt/
          - config/yttlib/
          - config/kapp.yaml
  valuesSchema:
    openAPIv3:
      properties:
        default_tls_secret:
          description: 'Optional: Overrides the config-contour configmap in namespace
            knative-serving.'
          examples:
          - tanzu-system-ingress/default-cert
          type: string
        domain_config:
          description: 'Optional: Overrides the config-domain configmap in namespace
            knative-serving. Must be valid YAML.'
          examples:
            example.com: |
              selector:
                app: nonprofit
          type: object
        domain_name:
          description: 'Optional: Default domain name for Knative Services.'
          examples:
          - example.com
          type: string
        domain_template:
          default: '{{.Name}}.{{.Namespace}}.{{.Domain}}'
          description: 'Optional: specifies the golang text template string to use
            when constructing the Knative service''s DNS name.'
          type: string
        ingress:
          properties:
            external:
              properties:
                namespace:
                  description: 'Optional: Only valid if a Contour instance already
                    present in the cluster. Specify a namespace where an existing
                    Contour is installed on your cluster (for external services) if
                    you want CNR to use your Contour instance.'
                  type: string
              type: object
            internal:
              properties:
                namespace:
                  description: 'Optional: Only valid if a Contour instance already
                    present in the cluster. Specify a namespace where an existing
                    Contour is installed on your cluster (for internal services) if
                    you want CNR to use your Contour instance.'
                  type: string
              type: object
            reuse_crds:
              default: false
              description: 'Optional: Only valid if a Contour instance already present
                in the cluster. Set to "true" if you want CNR to re-use the cluster''s
                existing Contour CRDs.'
              type: boolean
          type: object
        lite:
          properties:
            enable:
              default: false
              description: 'Optional: Not recommended for production. Set to "true"
                to reduce CPU and Memory resource requests for all CNR Deployments,
                Daemonsets, and Statefulsets by half. On by default when "provider"
                is set to "local".'
              type: boolean
          type: object
        local_dns:
          properties:
            domain:
              default: example.com
              description: 'Optional: Set a custom domain for CoreDNS. Only applicable
                when "local_dns.enable" is set to "true", "provider" is set to "local"
                and running on Kind.'
              examples:
              - example.com
              type: string
            enable:
              default: false
              description: 'Optional: Only for when "provider" is set to "local" and
                running on Kind. Set to true to enable local DNS.'
              type: boolean
          type: object
        nodeport:
          properties:
            enable:
              default: false
              description: 'Optional: Set to "true" to change envoy Service in contour-external
                from Type Loadbalancer to Type NodePort. On by default when "provider"
                is set to "local".'
              type: boolean
          type: object
        pdb:
          properties:
            enable:
              default: true
              description: 'Optional: Set to true to enable Pod Disruption Budget.
                If provider local is set to "local", the PDB will be disabled automatically.'
              type: boolean
          type: object
        provider:
          description: 'Optional: Kubernetes cluster provider. To be specified if
            deploying CNR on TKGs or on a local Kubernetes cluster provider.'
          examples:
          - local
          - tkgs
          type: string
      title: cnrs.tanzu.vmware.com.1.2.0 values schema
  version: 1.2.0
